greshake/i3status-rust

README.md
src/blocks/mod.rs
src/blocks/pacman.rs
src/icons.rs

I wrote up a block that checks the pending pacman updates. I'm not sure experienced in Rust so I'm hoping that this is all idiomatic. If there is something that should be different or could be done better please let me know :). I'm just trying to get a stronger handle on things.

Pacman Block

---

README.md

Just some small typos on the doc. @greshake, what is your opinion about break all the lines at every 80 columns? It is hard to edit text with a single line and at every word you change git can't help you showing only the word.
Cheers.

Fix some minor typos

---

src/blocks/pacman.rs

Calling out to a shell is not necessary for a bulk of the commands in `get_update_count`, it probably is bad practice to do so. This commit cleans `get_update_count` up and removes most of the shell-calls.
In addition, `run_command` has been changed to wait for the executed commands to exit. `Command::spawn` will spawn the processes without blocking, i.e. the program will continue with it's normal execution immediately, even though the desired result (e.g. the update of the pacman database) is not even completed yet.
The `trap` has been removed, since it either wouldn't have worked reliably (since the launched process was not kept track of) or it exited immediately, causing the `rm` call to the pacman lock to execute and delete any lock before the other processes are done.
Deleting the …

Refactor pacman block to use features of std

---

Cargo.toml
src/blocks/cpu.rs
src/main.rs
src/widgets/graph.rs
src/widgets/mod.rs

Created a graph widget. Was testing with the cpu block, but didn't include those changes because I didn't make that portion configurable yet.

Graph widget

---

src/themes.rs

Also replaces glyphs in source with utf notation.

Add new theme: Slim which uses material colors and transparency

---

src/blocks/battery.rs
src/blocks/cpu.rs
src/blocks/focused_window.rs
src/blocks/load.rs
src/blocks/memory.rs
src/blocks/music.rs
src/blocks/pacman.rs
src/blocks/sound.rs
src/blocks/temperature.rs
src/blocks/toggle.rs
src/blocks/xrandr.rs
src/main.rs
src/scheduler.rs
src/util.rs
src/widgets/graph.rs

Version: 0.1.8-nightly (cfec7ad2017-07-07)
As decided on #53 here is the update using the latest defaults for formatting.

Format according to the defaults in the latest rustfmt version

---

src/blocks/battery.rs
src/blocks/cpu.rs
src/blocks/custom.rs
src/blocks/memory.rs
src/blocks/music.rs
src/blocks/pacman.rs
src/blocks/sound.rs
src/blocks/temperature.rs
src/blocks/toggle.rs
src/blocks/xrandr.rs
src/main.rs
src/scheduler.rs
src/util.rs
src/widgets/button.rs
src/widgets/graph.rs
src/widgets/rotatingtext.rs
src/widgets/text.rs

Went through and fixed most of the clippy lints. Sorry this touches so many files, but most of the changes are pretty minimal. Mostly changing unwrap_or to unwrap_or_else, and overlapping match arms.

fix most clippy lints

---

Cargo.lock
README.md
src/blocks/battery.rs
src/blocks/disk_space.rs
src/blocks/focused_window.rs
src/blocks/load.rs
src/blocks/memory.rs
src/blocks/mod.rs
src/blocks/music.rs
src/blocks/pacman.rs
src/blocks/sound.rs
src/blocks/speedtest.rs
src/blocks/temperature.rs
src/blocks/toggle.rs
src/blocks/xrandr.rs
src/de.rs
src/errors.rs
src/icons.rs
src/main.rs
src/util.rs
src/widgets/graph.rs
src/widgets/rotatingtext.rs

Added speedtest block, organised the ReadMe so that all blocks would have the same formatting, ran the latest rustfmt, and did a minor dep upgrade, nothing is broken :D
If you want me to split off any of the changes into separate PRs feel free to tell me so.
Also my change to the `match_range` macro was to avoid using a temp variable to store the value of `vals[0]` as that is not a valid identifier.

Add speedtest block

---

src/themes.rs

I added a theme whose color schema matches the bad-wolf airline theme for vim (the "lemon bar" style: http://imgur.com/KOsmyN1). For some people who use this (quiet popular) color schema this one could be interesting ;)

[Added] bad-wolf theme

---

src/blocks/sound.rs

This PR modifies the Sound block to listen for ALSA events as a way to know that the block must be updated, as opposed to checking the volume every two seconds. This should dramatically reduce the number of updates to the block and make it much more responsive to users expecting visual feedback when changing the volume (e.g. as discussed in #101). However, it does mean spinning up another thread, which itself has a cost.
I haven't modified what is accepted in the block configuration -- the `interval` field is now simply ignored -- so existing configurations are not rejected.

Update the Sound block asynchronously instead of at a set interval

---

src/blocks/disk_space.rs
src/blocks/memory.rs

This is basically just a small refactor of something I noticed reading through the code. I'm not sure you're accepting this kind of submission yet.
There are a few enums in the DiskSpace and Memory blocks that are read from the configuration file as strings and then converted into enums through some sort of `from_str()` method. But one can just use `#[derive(Deserialize)]` to read into the enums directly. This will also make it easier to add more possible configuration values in the future -- just add a variant to the enum itself.

Use serde_derive to simplify reading more config enums.

---

src/blocks/net.rs

This PR adds a bitrate widget to the `net` block via `iwlist` (provided on Arch Linux by `wireless_tools`, a dependency of the original `i3status`).
In my quick search I didn't find a way of getting this information without another dependency but I am sure there is one.
I had `wireless_tools` installed as I still have `i3status` installed but that might of course not be the case for everyone.
Is there a standard way to signal that a certain setting requires a dependency? I thought about returning an error in the `bitrate` function but that would still execute the command every time an update is requested.
If the new dependency is not acceptable, then feel free to close this PR ;)

[Net block]: Add bitrate widget (using `iw`)

---

blocks.md

[blocks.md] Update `net` block description

---

src/blocks/battery.rs

Screenshots: 
Note: only tested on my device.

battery: display remaining time until battery is depleted/charged.

---

src/blocks/battery.rs

- added another else if to support energy_full/_current
A possible fix to #96, but given i know little about linuxs power supply class there might be a better fix.

Added support for energy

---

blocks.md
src/blocks/cpu.rs

Adds option to display average cpu core frequency in cpu block

cpu block: add optional cpu frequency display

---

Cargo.lock
Cargo.toml
src/blocks/disk_space.rs
src/blocks/music.rs

Updated all the dependencies, dbus and nix were the only ones that changed anything that alters our code

dependency updates

---

src/blocks/music.rs

Fixes #204 by using new definition of org_freedesktop_dbus::Properties

Fix music block only showing icon #204

---

src/blocks/battery.rs

Remaining time didn't work for me, because my machine doesn't have the `energy_now` and `power_now` files but only `charge_now` and `current_now`.
This makes it so that `energy/power` is used if available, then if not, `charge/current` is used, and if neither is present, an error is thrown.
I am relatively new to rust, let me know if i've done something suboptimally :)

Battery block: ability to calculate remaining time from charge/current

---

src/blocks/battery.rs

Change battery state to "Good" in charging mode. That changes also the highlight green when the battery is charging.

Change to State::Good in battery charging mode.

---

Cargo.lock
Cargo.toml

Should fix build on aarch64 (see https://github.com/NixOS/nixpkgs/pull/47566#issuecomment-425752132)

Update nix crate to 0.11

---

src/blocks/battery.rs
src/blocks/custom.rs
src/blocks/disk_space.rs
src/blocks/focused_window.rs
src/blocks/load.rs
src/blocks/memory.rs
src/blocks/music.rs
src/blocks/net.rs
src/blocks/networkmanager.rs
src/blocks/nvidia_gpu.rs
src/blocks/sound.rs
src/blocks/speedtest.rs
src/blocks/temperature.rs
src/blocks/template.rs
src/blocks/time.rs
src/blocks/uptime.rs
src/blocks/weather.rs
src/blocks/xrandr.rs
src/de.rs
src/main.rs
src/scheduler.rs
src/util.rs
src/widgets/button.rs
src/widgets/graph.rs
src/widgets/rotatingtext.rs
src/widgets/text.rs

I ran clippy on your project and solved most of the issues. 
Also I ran rustfmt (you should do this with a git hook IMHO, so it is always formatted).
I know this is a huge PR and I understand if you are not willing to accept all changes. Please say what you like or dislike and I will change that.

Run clippy 

---

src/main.rs
src/scheduler.rs

A proposed fix for #310 and very probably #290.

Process requests for update only  once

---

src/blocks/sound.rs

blocks/sound: Cleaner click handler

---

src/blocks/net.rs

If `hide_missing` is `false` (the default), the network symbol is shown with an
'×'.
If `hide_missing` is `true`, the network block is completely omitted.
Closes #121

Add `hide_missing` option for Network devices

---

blocks.md

Documentation for how the temperature block works

---

blocks.md
src/blocks/temperature.rs

blocks/temperature: Allow specifying temperature device

---

src/blocks/net.rs

Add on_click to net block. Convenient for opening network configuration panels.

blocks/net: Add on_click support

---

src/blocks/disk_space.rs

src/blocks/disk_space.rs: fix build on i686

---

src/blocks/disk_space.rs

You can see in this CI job how it failed before: https://travis-ci.org/void-linux/void-packages/jobs/595561765

fix builds on armv6

---

src/blocks/cpu.rs

I fucked up the last commit #455 (don't ask me how), this should fix it.

Don't dynamically allocate memory for no reason

---

blocks.md

Add kbddbus option to documentation

Update documentation for keyboard layout

---

src/blocks/focused_window.rs

Bandaid solution by adding a scheduled update within the block. This fixes #534 for now.

Temporary(?) fix for panic in #534

---

src/blocks/weather.rs

When connected to public wifi networks which require additional interaction
from the user to provide access, curl receives either 307 or 511, which
results in block error. Actually I think that only 2XX and 4XX status codes
should be further processed and JSON output parsed, everything else indicates
errors which will probably be recovered once the network access issues are
resolved.

Check HTTP response codes from curl in API calls

---

Cargo.lock
Cargo.toml
src/main.rs

Redo #541 but with `clap`

---

src/blocks/music.rs

It works in my machine(arch linux + mpd + mpDris2)
Edit: Closes #441.

Fix artist parsing from metadata

---

src/blocks/nvidia_gpu.rs

Creating pull-request for #564
Edit: Closes #564.

NVIDIA GPU Block - Fixed Utilization Width (Issue #564)

---

src/blocks/net.rs

I'm using Ubuntu with a PPTP vpn. (configured via `gnome-control-center`).
The device gets the name `ppp0`. With `device = "ppp0"` in the net block, it showed up as inactive / missing.
The uevent file has `DEVTYPE=ppp`. I'm assuming that's how `wireguard` is done, so I copied the same logic for `ppp`, which works.

feat(net): support ppp vpn

---

blocks.md
src/blocks/ibus.rs

Makes the block much more bar friendly.

IBus block: Allow mapping of displayed engine to user configured value

---

src/blocks/battery.rs
src/blocks/cpu.rs
src/blocks/disk_space.rs
src/blocks/memory.rs
src/blocks/net.rs
src/blocks/sound.rs
src/util.rs

Implementation for https://github.com/greshake/i3status-rust/issues/577

Add support for progress bars to some blocks

---

src/blocks/maildir.rs
src/blocks/notmuch.rs

Remove unnecessary braces

---

src/blocks/sound.rs

added mapped-volume option for correct volume

---

src/blocks/battery.rs

Alternative implementation following discussion on https://github.com/greshake/i3status-rust/pull/479:
Add critical, warning, info and good thresholds to the block configuration. The order of states as the battery discharges is as follows:
Good -> Idle -> Info -> Warning -> Critical
This slightly overcomplicated choice of states allows the default configuration to remain as it was before (with the Idle state non-existant between 60 & 60), while also allowing a more conventional battery status indicator that doesn't draw attention except at low and critically low levels (Setting info == warning and good == 100 effectively disables these states).

battery: Add configurable thresholds

---

src/blocks/battery.rs
src/blocks/bluetooth.rs
src/blocks/custom.rs
src/blocks/ibus.rs
src/blocks/keyboard_layout.rs
src/blocks/net.rs
src/blocks/speedtest.rs
src/blocks/uptime.rs
src/blocks/weather.rs
src/errors.rs
src/input.rs
src/util.rs

These shouldn't cause any problems

tree-wide: fix trivial Clippy warnings

---

blocks.md
src/blocks/sound.rs

sound block: make -M and ALSA device configurable

---

src/blocks/bluetooth.rs
src/blocks/cpu.rs
src/blocks/ibus.rs
src/blocks/keyboard_layout.rs
src/blocks/music.rs
src/blocks/net.rs
src/blocks/pomodoro.rs
src/blocks/sound.rs
src/blocks/toggle.rs
src/blocks/weather.rs
src/util.rs

Should be no known issues with changing these as per clippy's suggestion.

Fix clippy lints

---

src/blocks/nvidia_gpu.rs

nvidia block: make threshold configurable, swap idle/good

---

src/blocks/net.rs

As mentioned here: https://github.com/greshake/i3status-rust/issues/399#issuecomment-520248550

net block: auto select default device

---

src/blocks/time.rs

time block: only register left mouse button clicks

---

src/themes.rs

Use good_bg and good_fg theme overrides

---

src/blocks/net.rs

net block: fall back to operstate if carrier not readable

---

blocks.md
src/blocks/weather.rs

weather block: allow city to be given by name

---

src/blocks/weather.rs

Using https for weather info retrieval from api.openweathermap.org

---

blocks.md
src/blocks/weather.rs

weather block: add humidity and apparent temp format specifiers

---

blocks.md
src/blocks/networkmanager.rs
src/icons.rs

networkmanager block upgrade

---

src/blocks/backlight.rs

backlight: special case for amdgpu backlight

---

blocks.md
src/blocks/net.rs

net block: add ipv6 option

---

src/blocks/net.rs

net block: add fallback to `wpa_cli` for retrieving SSID

---

profiling.md

Add a short document explaining how to use the `profiling` feature to profile a block.

Add profiling.md

---

src/util.rs
src/widgets/button.rs

Escape pango text to prevent errors

---

src/blocks/net.rs
src/blocks/networkmanager.rs

Some more trivial ones + rustfmt afterwards.

clippy: fix lints

---

src/blocks/sound.rs
src/icons.rs

Fixes #598 
This includes the changes in #517.

Update font awesome icons to version 5

---

src/icons.rs

Fix small bugs for icons

---

src/blocks/net.rs

Resolves the cognitive complexity clippy warning and improves the readability (I hope)

Refactor net block update

---

src/blocks/battery.rs

My battery (cw2015-battery) does not support any of the current properties used to calculate the remaining time (doesn't have `energy_now` or `charge_now` in sysfs). However, it does have its own `time_to_empty_now`. This PR changes the `time_remaining` function to simply read from `time_to_empty_now` if it exists, and otherwise falls back to the existing calculation.
* Is `time_to_empty_now` commonly available? Is it a "standard" name? Are there similar files with slightly different names but the same purpose, which could be tried on other devices?
* When charging, `time_to_empty_now` is 0. There is no corresponding `time_to_full_now` for my device: Are there other devices which have both and should conditionally read one or the other based on charging status? 
* Are there any situations …

battery: read remaining time from time_to_empty_now if it exists

---

src/blocks/battery.rs

Reverts greshake/i3status-rust#659
Didn;t notice the other PR

Revert "battery: read remaining time from time_to_empty_now if it exists"

---

blocks.md
src/blocks/keyboard_layout.rs

keyboard_layout: add sway driver

---

src/blocks/focused_window.rs

Resolves https://github.com/greshake/i3status-rust/pull/532#issuecomment-581854186
@travankor

focused_window block: show marks with brackets like sway does

---

src/blocks/focused_window.rs

This fixes https://github.com/greshake/i3status-rust/pull/672#issuecomment-627794457 for me. @travankor, hopefully this does it for you as well.

focused_window block: cleanup marks handling

---

.travis.yml
src/blocks/music.rs

Enable clippy linting in travis

---

src/blocks/keyboard_layout.rs

This should fix the CI failures for any new commits from now

fix last remaining clippy lints

---

blocks.md
src/blocks/focused_window.rs

@travankor this should complete your feature request

focused_window block: allow show_marks to hide underscored marks

---

src/blocks/net.rs

This is possible as `ip` has a JSON output option.
TODO

Use serde_json to get ip address instead of sed

---

src/blocks/net.rs

Reverts greshake/i3status-rust#513 as there appears to be a bug in Debian's `ip` as mentioned in https://github.com/greshake/i3status-rust/pull/513#commitcomment-39226333
What we can do next:
1.    Fallback to parsing ip output using sed if cannot parse address from JSON. However this would mean the ip command would be run twice, plus having to keep around the previous code. Not really something I want to do.
2.    Check the first member of the JSON array, and if it is empty then try the next member. This will lead to some code duplication but it would solve this issue.
3.    Investigate bug origin and possibly reinstate the PR.

Revert "Use serde_json to get ip address instead of sed"

---

src/blocks/battery.rs

Otherwise, fall back to original calculations for time_remaining.
w.r.t. the code, I think the general idea is ok (collect possible sources of information as `Options`/`Result`s, then calculate the time based on the charging status and available info sources), but I suspect the code could be cleaner. There is some potential to optimise by not reading more values once we've found a suitable source, but due to the fact there are two calculations (time to empty vs. time to full) which sometimes use the same values (`fill`, `full` & `usage`) it would add some complexity, or wouldn't handle situations where e.g. `time_to_empty_now` can be read directly but `time_to_full_now` cannot and needs to be calculated.
Also, I'm not sure what this line is supposed to do, so I've basically left it alone. …

battery: read remaining time from time_to_empty_now and time_to_full_now if they exist

---

src/blocks/net.rs
src/blocks/speedtest.rs
src/util.rs

Resolves #706 
@GladOSkar Just a quick mockup for now, is this what you had in mind?
TODO
- move common code to util.rs
- update docs

speedtest block: improve throughput formatting

---

blocks.md
src/blocks/kdeconnect.rs
src/icons.rs

See https://github.com/greshake/i3status-rust/pull/717#issuecomment-638152064
Haven't tested yet but it should work assuming the "reachable" flag supplied by kdeconnect is accurate.

kdeconnect: detect disconnections

---

src/blocks/kdeconnect.rs

kdeconnect: automatically discover even unreachable devices

---

tests/run_binary.rs

tests: only run debug/release test as appropriate

---

src/blocks/sound.rs
src/main.rs

Re-add feature flag for pulseaudio

---

src/blocks/sound.rs

Add feature flag for recently added pulseaudio code (device_kind)

---

.github/workflows/rust.yml

For some reason Travis CI isn't running anymore so figured we may as well try out GitHub Actions

Update workflow for GitHub Actions

---

src/blocks/net.rs

https://github.com/greshake/i3status-rust/issues/766
Defining the deprecated option was taken as true though it being false. This has been fixed.
Logic for checking boolean/format style has been changed.

fix for issues-766

---

blocks.md

Fix wiki to reflect actual configuration options

Fix error in networkmanager block docs

---

src/blocks/pacman.rs
src/blocks/taskwarrior.rs

Latest PR messed up the formatting of `taskwarrior.rs` and it failed the checks.
EDIT: Also a small clippy error on `pacman.rs`

taskwarrior.rs formatting

---

blocks.md
src/blocks/sound.rs

Resolves #783 
This should do the job for now

sound block: add `max_vol` config parameter

---

src/blocks/battery.rs

This pull request adds an optional field like `full_format` to the battery block's config to allow users to customize the text when the battery is full. For example, users can use this to show the percentage or some other texts.
See issue #784 for more details.

battery block: add full_format to show text when battery is full

---

src/blocks/temperature.rs

Reverts changes made in #801
If more precision is required it can be re-added once #750 is implemented

temperature block: change type back to int

---

src/blocks/net.rs

Iterate over ip json arrays

---

blocks.md
src/blocks/music.rs
src/widgets/rotatingtext.rs

couldn't quite figure out the best way to pass the id into the rotatingtext widget. but this does the job. i'm new to rust :)

add on_click for music block + add `id` field for rotating text

---

src/blocks/hueshift.rs

This PR fixes the `unreachable pattern` warning for the hueshift module.
```
warning: unreachable pattern
--> src/blocks/hueshift.rs:226:9
|
226 |         Some(_sct) => {
|         ^^^^^^^^^^
|
= note: `#[warn(unreachable_patterns)]` on by default
warning: unreachable pattern
--> src/blocks/hueshift.rs:245:9
|
245 |         Some(_sct) => {
|         ^^^^^^^^^^
```
Previously there were some match blocks that were trying to match on specific strings. Since that's not how Rust's match works, the block always used `redshift` and never `sct`.
This PR introduces a proper Enum for configuration parameter parsing and matching.
This has been tested with both `redshift` and `sct`. Scrolling and clicking both work as intended.

[Bug] Fix sct hueshift and remove warning

---

src/blocks/custom_dbus.rs
src/blocks/disk_space.rs
src/blocks/kdeconnect.rs
src/blocks/music.rs
src/config.rs
src/widgets/rotatingtext.rs

This removes all current clippy issues and compiler warnings except the one for `hueshift`, which is addressed in the other PR.

[Code cleanup] Fix warning and clippy issues

---

src/blocks/battery.rs

This somehow managed to slip through the "allow missing battery" PR :sweat:

Fix mutable variable in battery.rs

---

README.md

These documentation changes address some of the troubles I personally had when I set up i3status-rust :)

Documentation improvements for top level configuration and font installation

---

src/blocks/sound.rs

sound block: fix build error when pulse disabled

---

src/blocks/nvidia_gpu.rs

nvidia block: don't crash when gpu is disabled

---

blocks.md
src/blocks/custom.rs

custom block: add option to hide block when output is empty

---

src/blocks/music.rs

music block: only respond to left clicks

---

src/blocks/net.rs

net block: fix iwctl ssid regex

---

src/blocks/net.rs

net block: do not error out block unnecessarily

---

src/widgets/graph.rs

graph widget: remove underscore

---

src/blocks/net.rs

Revert #869

---

blocks.md
src/blocks/music.rs

music block: add option to ignore certain players

---

blocks.md
src/blocks/music.rs

In similar vein as other blocks such as bluetooth, net, etc.

music block: add `hide_when_empty` option

---

src/blocks/music.rs

music block: do not respond to scroll events from other blocks

---

src/blocks/music.rs

Currently the block subscribes to MPRIS PropertiesChanged signals and then
schedules an update unconditionally whenever it received a signal. Then inside the
update() function, multiple calls are made to retrieve the Metadata,
PlaybackStatus or even to grab a new player. Not only are all these calls
redundant, the block is also unable to keep track of players which disappear
from the bus without emitting a PropertiesChanged signal (for example mpv).
In addition, there are often signals sent in which the Metadata/PlaybackStatus
has not actually changed, yet we schedule an update regardless.
Changes with this PR:
- each PropertiesChanged signal actually contains the new values of the
properties that were changed, so we will grab them from here instead of
making another method call.
- in …

music block: overhaul update mechanism

---

src/blocks/disk_space.rs

diskspace block: fix panic when no icon defined

---

src/blocks/music.rs

Resolves #913
﻿
Need to redo the click handler at some point but this should do for now

music block: limit mouse events when no players available

---

src/blocks/kdeconnect.rs

kdeconnect: handle -1 values for battery charge

---

src/blocks/music.rs

As mentioned in https://github.com/greshake/i3status-rust/issues/808

music block: allow right click to cycle between available players

---

blocks.md

@ammgws thanks for your work on 930. it works well for me!

update music block docs for new cycling feature. see #930

---

src/blocks.rs
src/blocks/apt.rs

From limiting testing it seems to work... I will leave it undocumented for now.
@GladOSkar  You wouldn't happen to be running Ubuntu or something?

Add new Apt block

---

src/blocks/music.rs

This adds a `format` string to the music block.
This is part of what will hopefully be a series of improvements made to the music block that address points made by @Brod8362 when he proposed his new `mpd` block (#836). Since we are limited by what information is on the MPRIS bus it may not be as featureful as a native implementation for each possible music player, however it is better than nothing.
TODO: add support for optional MPRIS fields as well? (though they will end up blank when a player doesn't support it)
Testers welcome.

music block: implement format string

---

blocks.md

Resolves #936 via documentation

docs: mention places where escaping Pango chars may be required

---

blocks.md
src/blocks/music.rs

- music block: allow right click cycle when block is collapsed
- music block: do not clear metadata unnecessarily

music block bug fixes

---

src/blocks/music.rs

music block: add workaround for `playerctl`

---

blocks.md
src/blocks/pacman.rs

pacman: add option to hide when block up to date

---

src/blocks/xrandr.rs

xrandr: do not leave zombies around

---

src/blocks/net.rs

net block: fix overflow panic 

---

src/blocks/net.rs

This was previously behind a config option `auto_device`, however it was undocumented.
Rather than introduce another config option, it is better to just default to auto-discovery
if `device` is not set in the block config, as the current docs currently say.
Resolves #987 
TODO: remove loopback device fallback?

net block: always auto-discover devices if not explicitly set in config

---

src/blocks/net.rs

Resolves #997﻿
Block could do with some refactoring though...

net: skip empty entries in ip -json output

---

src/blocks/apt.rs
src/blocks/memory.rs
src/blocks/notmuch.rs
src/blocks/pacman.rs
src/blocks/taskwarrior.rs

I forget to check various blocks to use id for the widget events name in #1006 such that some blocks 'on_click' event do not work.
It should fix #1012.

Fixes #1012

---

.gitignore
src/blocks/github.rs
src/blocks/hueshift.rs
src/blocks/maildir.rs
src/blocks/music.rs
src/blocks/speedtest.rs
src/blocks/weather.rs
src/blocks/xrandr.rs
src/util.rs
src/widgets/rotatingtext.rs

Just some refactoring. Make clippy happy.

refactoring: fix all clippy warnings

---

src/blocks/kdeconnect.rs

Things that changed in the latest kdeconnect ver: battery (https://github.com/KDE/kdeconnect-kde/commit/f90d6a019ff288c4a16f91c2d7baa617ce793077) and notification plugins (https://github.com/KDE/kdeconnect-kde/commit/4439e7c662c7829ba930efd0cbc504b533e02a26)
Resolves #974
kdeconnect v20.11.80 new
kdeconnect v20.08.03 old

kdeconnect: update for new D-Bus structure

---

README.md

[Source](https://github.com/greshake/i3status-rust/blob/f4ee3e7ac97cead50f17b247feb9be7198bed507/src/config.rs#L115)

README: fix scrolling default value

---

src/util.rs

add TODO regarding clamp()

---

src/blocks/memory.rs

memory: fix `clickable`

---

src/widgets/button.rs
src/widgets/graph.rs
src/widgets/text.rs

cast IDs to strings in json

---

src/blocks/music.rs

music: fix on_collapsed_click

---

src/blocks/net.rs

fix net: typo

---

src/blocks.rs

The wiki is not actively maintained, but is has some good documentation for `Block` and `BlockConfig` traits. Also, if I'm not mistaken, there is no way to contribute to the wiki.

Copy some docs from the wiki to the code

---

src/blocks/net.rs
src/blocks/sound.rs
src/widgets/text.rs

Improve #1071 and #1072. Fix issues like #1001 for every block (in theory).

`set_text()`: check whether the content is empty

---

src/blocks/music.rs

music: fix spacing

---

blocks.md
src/blocks/net.rs

net: remove explicit `clickable` option

---

src/blocks/net.rs

Improve #1079 a little bit: remove `is_clicked`, swap `format` and `format_alt` on click.

Improve #1079

---

src/main.rs
src/util.rs
src/widgets/i3block_data.rs

Another bugfix for #1085. Escape json and fix error displaying.

I3BlockData: escape json

---

src/widgets/i3block_data.rs

Remove trailing comma

---

src/util.rs

Fix formating: do not ignore text after the last placeholder

---

blocks.md
src/blocks/backlight.rs

Closes #1096
- #183
- #452
- #573
- #845
- #1081

backlight: add `invert_icons` config option

---

src/blocks/networkmanager.rs

When a VPN is enabled there's two connections created:
- One with the property "VPN = True" and "Devices" set to the upstream interface (for example the wireless connection over which the vpn is created)
- The other one with "VPN = False" and "Devices" set to the actual vpn device (tun0, vpn0, or whatever)
Since the first one only return a device which is already listed on another connection (the actual wireless connection for exemple), we can ignore it.
This patch ignore all connections with the property "VPN = True"
Fix #1016

networkmanager: Avoid duplicate device with VPN connections.

---

Cargo.toml
src/blocks.rs

Make `maildir` an optional dependency

---

src/blocks/kdeconnect.rs

When checking the version by trying to make a D-Bus call to the new API, i3status-rust could be up and running before kdeconnect itself is, which would give a false result.
Let's just call the executable and get the info that way. This should be reliable as we only need to check whether the output matches that of the old version of kdeconnect, so it doesn't matter if the output format changes in future versions.
﻿
Comparing the output of different kdeconnect versions (using Arch packages)
`kdeconnect-cli --version 2>/dev/null`
kdeconnect 1.3.4-1: `kdeconnect-cli 1.3.4`
kdeconnect 1.4-2: `kdeconnect-cli 1.4.0`
kdeconnect 20.03.80-1: `kdeconnect-cli 1.4.0`
kdeconnect 20.03.90-1: `kdeconnect-cli 1.4.0`
kdeconnect 20.04.0-1: `kdeconnect-cli 1.4.0`
kdeconnect 20.07.80-1: `kdeconnect-cli 1.4.0` …

kdeconnect: change version check mechanism

---

src/blocks/music.rs

Also: initialize `Player` struct when a new player is created.

music block: merge two threads into one

---

src/blocks/bluetooth.rs
src/blocks/notify.rs

Fix notify and bluetooth blocks

---

src/main.rs

Implement config reloading

---

example_config.toml

This PR is an attempt to fix #1130

Udate example config with new placeholder format

---

src/main.rs

No more restarting `sway` after making a typo in the config!

Allow reloading with usr2 signal after displaying error

---

Cargo.lock
Cargo.toml
doc/blocks.md
src/blocks/net.rs
src/widgets/text.rs

Net block: use https://github.com/Eonm/nl80211 to get WiFi information.

Net block: use nl80211 to get WiFi information

---

NEWS.md

Update Links to `blocks.md` in `NEWS.md`

---

src/util.rs

This error made the bar change it's size.

format_vec_to_bar_graph(): fix logic error

---

src/formatting/value.rs

Do not apply engineering notation to values without units

---

src/blocks/custom.rs
src/widgets/text.rs

Resolves #1156
Regressed in #1135, feedback welcome

Allow custom blocks with JSON not to set an icon

---

man/generate.sh
man/i3status-rs.1

Also realised we have the "back to the top" stuff in the man as well but I guess it's better than nothing.

regenerate man

---

src/blocks/apt.rs

Fix apt block

---

src/blocks/net.rs
src/formatting/placeholder.rs

Partially resolves https://github.com/greshake/i3status-rust/issues/1155#issuecomment-815021231

Fix a typo

---

README.md

The link is currently displaying a 404 page.
Thanks for this project, it looks cool :)

README.md: Update blocks documentation link

---

src/blocks/net.rs
src/formatting.rs

Introduce `FormatTemplate::contains()`; fix net block

---

src/blocks/net.rs

Relevant comment https://github.com/greshake/i3status-rust/issues/1069#issuecomment-817090540

Net block: do not throw an error if frequency/signal is unavailable

---

src/formatting/value.rs

formatting: better unicode support

---

src/blocks/disk_space.rs

disk_space: fix alert_absolute

---

doc/blocks.md

Add apt on_click example

---

src/blocks/weather.rs

Remove quotes from weather block

---

doc/themes.md

Improve theming documentation somewhat

---

src/blocks/custom_dbus.rs

custom_dbus: Unset icon if empty.

---

Cargo.lock
Cargo.toml
src/blocks/battery.rs
src/blocks/custom_dbus.rs
src/blocks/networkmanager.rs

Preparations for releasing v0.2

chore: bump deps

---

src/blocks/pacman.rs

fixed pacman printing to stdout/err

---

src/blocks/memory.rs

Resolves #1216
Not sure what the current policy on shelling out is, but this should be fast enough and is way shorter than anything i could come up with using native code.
Feedback welcome :)

memory: Count ZFS arc cache to cache to exclude from used memory

---

src/blocks/custom.rs

Better error message on custom blocks

---

doc/blocks.md
src/blocks/battery.rs

blocks: Add function to find default battery

---

src/blocks/net.rs

Resolves #1271
Use a regex to find only valid escape sequences, not just backslashes.
Everything else is kept literal, this should not be able to fail ever.
Feedback welcome

Fix SSID escape code decoding

---

src/blocks/temperature.rs

The temperature block used the `has_command` to check for `-j` support.
But `has_command` only works if the binary can be executed. The commit
searches for json output support in the `--help` ouput to determine the
fallback property.
fixes #1273

fix `temperature` block fallback

---

src/blocks/networkmanager.rs

networkmanager: Update DBus interface

---

doc/blocks.md
src/blocks/github.rs
src/blocks/nvidia_gpu.rs
src/blocks/temperature.rs
src/errors.rs
src/main.rs

Changed Nvidia_gpu block to use the interval argument of nvidia-smi, and added sysfs backend for Temperature block, as I personally dislike constantly spawning lots of processes if it can be avoided. Some relevant discussion in #469.
Added colour theme support to Github block to make it much easier to tell when it changes. Allows setting different colours depending on notification type.
Change recommended pacman hook to use SIGUSR1 to merely force an update rather than restarting.

Github, Nvidia_gpu, Temperature block additions and changes

---

src/blocks/nvidia_gpu.rs

ab2f7bbe2e changed to running nvidia-smi once and reading lines one at a time
but any delay in running update would lead to multiple lines being buffered
and never catching up, if any other blocks have a long running time or with
a non integer interval it would fall further behind every update
Read over all lines currently in buffer instead and use the most recent

Fix nvidia block falling behind on lines from nvidia-smi

---

src/blocks/cpu.rs
src/blocks/time.rs
src/formatting.rs
src/util.rs

https://github.com/greshake/i3status-rust/blob/db144a00a29c8fabaee7cf22dbd7984401ed0619/src/blocks/cpu.rs#L188
https://github.com/greshake/i3status-rust/blob/db144a00a29c8fabaee7cf22dbd7984401ed0619/src/blocks/cpu.rs#L195
Yes, there is.

refactor: FormatTemplate::render(): accept generic hashmap

---

src/blocks/custom_dbus.rs

custom_dbus: add option to clear contents after timeout expires

---

src/blocks/ibus.rs

Instead of erroring out the whole bar when calls to Global Engine fail,
instead just display placeholder text. This is required at least on my system,
since the first call to global engine returns 'no global engine' even when IBus is up and running.
It only starts returning an engine after the engine has been specifically set using `ibus engine mozc-jp` etc.
Bad practice but this commit also includes some other changes:
- Some stderr print statements for debugging purposes, likely
to come in handy in the future
- Add ability to customize the initial text / text when global engine not found

ibus block: tolerate errors better

---

src/blocks/docker.rs

docker: expand socket path

---

doc/blocks.md
src/blocks.rs
src/blocks/rofication.rs

Rofication is the notification system used by regolith linux (and others I assume, but this is my use case).
It's a simple system - there's a daemon that receives the notications on d-bus and that exports them via a UNIX socket. The block itself just needs to display a counter and a color (based on any notification being critical or not) and spawn the GUI when clicked.

Create rofication block

---

src/blocks/rofication.rs

No functional changes, just take care of clippy's suggestions.

rofication-block: Solve clippy messages

---

src/blocks/rofication.rs

Implement Max's suggestion here
https://github.com/greshake/i3status-rust/pull/1390#pullrequestreview-845756555

Rofication: Remove extra allocation

---

src/blocks/sound.rs

When adding a sound block using the auto/pulseaudo driver and specifying
a device name:
For example:
```
[[block]]
block = "sound"
name = "alsa_output.pci-0000_41_00.1.hdmi-stereo-extra2"
```
The device volume is unknown. This results in an error being thrown when
when you try to modify the volume (for example by scrolling over the
block to change it by step).
The workaround I'd used was to also set a custom block that would modify
the volume (slightly) so that the mainloop would pick up the change,
like this:
```
[[block]]
block = "custom"
command = "pactl set-sink-volume
alsa_output.pci-0000_41_00.1.hdmi-stereo-extra2 +1"
interval = "once"
hide_when_empty= true
```
Instead of creating a `PulseAudioSoundDevice` pointing at the default
device and then mapping the device using `with_name` …

Named PA sound devices don't know current volume

---

src/blocks/hueshift.rs

The hueshift block spawn zombie processes when interacted with, similar to what is described in #988.
I fixed it the same way it was in #990, with `spawn_child_async`.

hueshift: do not leave zombies

---

src/blocks/battery.rs

Fixes #1405
@FlorianFranzen pointed out two issues.
1. I changed how we matched the `device` to the `device_path`.
2. `DisplayDevice` does no longer work with `allow_missing`
First we can restore the original logic that was in place for how a
`device` to the `device_path`.
Second the `DisplayDevice` is not in the `EnumerateDevices` so we need
to account for that in is_available.

Issue 1405

---

examples/config.toml
src/blocks.rs
src/blocks/base_block.rs
src/main.rs

add if_command field to block config

---

src/blocks/custom.rs

In i3blocks, a block can be specified with interval "persist", which means its associated command runs as a child of i3blocks. Each line on that process's stdout is used to update in the block in realtime. I used this functionality to display MQTT messages in my statusline (with `mosquitto_sub`).
This PR adds similar functionality -- set a `custom` block's `persistent` config key to `true`, and its associated command will be run persistently; each line will update the block's contents.
I've tested to make sure that this doesn't break regular `command` and `cycle` functionality but haven't gone beyond that. I'm using this patch right now to run [a pomodoro tool](https://gist.github.com/an-empty-string/a4706537cd9ffaf5f67d3f49a8540fea) that talks MQTT and it seems to be working reliably so …

Implement "persist" command feature from i3blocks

---

doc/blocks.md
src/blocks/temperature.rs

it was deprecated since 0.21.3

temperature: remove sysfs driver

---

doc/themes.md

It was introduced in https://github.com/greshake/i3status-rust/commit/25bf1a32504046a5f42c0207e4603ee265837c23

doc/themes: add awesome6 icon theme

---

src/blocks/net.rs
src/netlink.rs

Addresses third point in #1498

net: detect misssing and inactive devices

---

Cargo.toml
src/blocks/sound.rs
src/blocks/sound/alsa.rs
src/blocks/sound/pulseaudio.rs

sound: make pulseaudio optional again

---

src/blocks/custom.rs
src/config.rs

custom: recover from invalid json errors

---

src/blocks/keyboard_layout.rs

Not sure if this is my bad but I had to add this line to get the keyboard block to show up

Set widget in keyboard_layout block

---

man/i3status-rs.1
src/blocks/battery.rs
src/blocks/battery/apc_ups.rs

Add apc_ups battery driver

---

src/blocks/weather.rs

At the time of implementing the feature there was no API parameter, but
it was introduced a few months later. According to OpenWeather[^1], they
used Australian Apparent Temperature (AT), so the results should be the
same. Therefore, this commit serves as a cleanup, code simplification.
References:
[^1]: <https://openweather.co.uk/blog/post/new-feels-temperature-openweather-apis>

Use API data for AT instead of calculating

---

src/blocks/pacman.rs

fakeroot can be run directly without sh indirection.
Needs verification that it works not only for me.

pacman: don't use sh to run fakeroot

---

src/blocks/custom_dbus.rs

custom_dbus: allow override of interface name with env var

---

src/blocks/weather.rs
src/blocks/weather/met_no.rs
src/blocks/weather/open_weather_map.rs

weather: do not use city name with autolocate

---

src/blocks/net.rs
src/errors.rs
src/netlink.rs

fixes #1515
fixes #1595
fixes #1069
notfixes #587
Needs testing.

net: implement ip&ipv6

---

src/blocks/net.rs
src/netlink.rs

net: support regex for `device` option

---

src/blocks/docker.rs
src/blocks/notmuch.rs
src/blocks/rofication.rs
src/blocks/taskwarrior.rs
src/blocks/watson.rs

docs: mention path expansion support

---

src/netlink.rs

net: fix Interface::is_up

---

src/blocks/custom.rs

custom: fix hide_when_empty for json

---

src/blocks/nvidia_gpu.rs
src/formatting.rs
src/formatting/value.rs
src/widget.rs

Fixes #1560
Fan control off:
Fan control on:

nvidia_gpu: do not highlight individual values

---

src/blocks/backlight.rs

This PR adds a workaround for [`ddcci`](https://aur.archlinux.org/packages/ddcci-driver-linux-dkms), a well as minimizes the number of reads of brightness file and fixes a bug when if backlight block receives "UpdateRequest", it will stop responding to clicks until brightness changes.

backlight: add a workaround for ddcci

---

Cargo.lock
Cargo.toml
src/themes/color.rs

Remove color space

---

src/blocks/notify.rs

See https://github.com/ErikReider/SwayNotificationCenter

Add support for SwayNotificationCenter driver

---

files/icons/awesome.toml
files/icons/awesome5.toml
files/icons/awesome6.toml
files/icons/material-nf.toml
files/icons/material.toml
src/blocks.rs
src/blocks/tea_timer.rs

Timer for a general timer, that adds 30s each time you click on it. I did it for my personal use, don't hesitate to close the PR if you think it has no place upstream.

Add block for a tea timer (or any timer, really)

---

src/blocks/battery.rs

It is possible for a battery to be in the "Not charging" state, in multi-battery setups especially, where both batteries may be partially drained, but only one will be being charged at once. In such cases the battery block incorrectly reports the non-charging battery as full.
In order to not break existing behaviour, and also given as mentioned in continue to report "Not charging" batteries to be full by default.
Fixes #1416.

Add `not_charging_format` config option

---

doc/blocks.md

Specifying the implementation for a microphone block

update docs #1692

---

src/blocks/bluetooth.rs

bluetooth: handle the case when .get_managed_objects() returns Err

---

src/blocks/notify.rs

Left-clicking on this block will show notifications.
Right-clicking on this block will enable/disable notifications.
Add flag so that when there are notifications you could show the number of events.
Set widget state if there are notifications.
Depends on dunst-project/dunst#1127 for dunst notification count.
Please let me know if you have any thoughts on the design, format variable names,  if there's any other clever way to not need the `notifications` flag to achieve the same goal, or widget states.

Notification counts and show messages

---

src/blocks/tea_timer.rs

Usage:
```toml
[[block]]
block = "tea_timer"
done_cmd = "notify-send 'Timer Finished'"
```

tea_timer: add done_cmd option

---

src/blocks/apt.rs

Apt seems to almost always hold a few phased updates back, for Ubuntu 22.04 at least. This makes the update indicator less useful. The logic appears to be that [anything under 100% might be held back based on the machine ID](https://salsa.debian.org/apt-team/apt/-/commit/c5bc86d45e003905ef411146e66b414d26fb1ff8). I added the option to filter out potentially held back packages from the update count.
The implementation just parses the package name from the apt list lines that were previously tallied raw, e.g.
```
gnome-initial-setup/jammy-updates 42.0.1-1ubuntu2.1 amd64 [upgradable from: 42.0.1-1ubuntu2]
```
finds the phase % from apt-cache if it's there, e.g.
```
$ apt-cache policy grub-efi-amd64-bin
grub-efi-amd64-bin:
Installed: 2.06-2ubuntu10
Candidate: 2.06-2ubuntu14
Version table: …
```

apt: Add option to ignore waiting phased updates

---

src/blocks/music.rs
src/blocks/sound.rs

This is just a draft for now.  It add's individual volume controls per player. I keep my master volume at 100% and set each player volume independently.
It depends on changes in ~~#1710~~, ~~#1718~~ and ~~#1720~~.
As those are merged I will rebase this to de-duplicate the duplicated commits.

MPRIS music volume

---

src/blocks.rs
src/blocks/service_status.rs
src/errors.rs

Add service_status block

---

src/blocks/battery/upower.rs

Fix UPower when device is missing

---

src/formatting/formatter.rs

Fix time block locale

---

src/blocks/music.rs

music: make volume optional

---

src/blocks/music.rs

small typo fixes in `music.rs` block

fix typo for 'play' and 'preferred'

---

src/blocks/time.rs
src/formatting/prefix.rs

Implement cycling through timezones in "time" block on click

---

CONTRIBUTING.md
NEWS.md
files/icons/material-nf.toml
src/blocks/battery/sysfs.rs
src/blocks/github.rs
src/blocks/hueshift.rs
src/click.rs
src/formatting.rs
src/main.rs
src/protocol/i3bar_event.rs
src/widget.rs

I was looking into another spell check tool (https://crates.io/crates/typos) and found some more errors.
https://pre-commit.com seem like it will be a useful tool for making sure collaborators have code.

Fix more typos

---

src/blocks/backlight.rs

backlight: reconnect after monitor sleeps

---

src/blocks/time.rs

time: implement `prev_timezone` action

---

cspell.yaml
src/blocks/vpn.rs
src/blocks/vpn/mullvad.rs
src/blocks/vpn/nordvpn.rs

Added MullvadDriver in vpn widget

---

Cargo.lock
Cargo.toml
src/escape.rs
src/formatting.rs
src/formatting/formatter.rs
src/main.rs

Allow custom separator for rotating text

---

src/blocks/apt.rs
src/blocks/dnf.rs
src/blocks/github.rs
src/blocks/pacman.rs
src/blocks/sound.rs
src/blocks/watson.rs

- Easier to read and understand
- A bit shorter
- Requires Rust 1.70 (1 June, 2023)

use is_some_and(..) instead of map_or(false, ..)

---

src/blocks/battery/sysfs.rs

Make sysfs debug formatting consistent

---

src/formatting/formatter.rs
src/formatting/prefix.rs

Fix `.eng` formatter: inconsistent rounding

---

src/blocks/pacman.rs

See https://github.com/greshake/i3status-rust/issues/1561#issuecomment-1697865332
This is a breaking change.

pacman: create a checkup-db dir per user

---

doc/themes.md
files/icons/emoji.toml

Only half serious about this...

Add new emoji icon set 🙂

---

src/blocks/weather.rs
src/blocks/weather/open_weather_map.rs

Use lat/lon for Open Weather Map

---

src/blocks/xrandr.rs

xrandr: support multiple outputs

---

src/click.rs
src/protocol/i3bar_event.rs

Fail if click handler refers to unknown button

---

src/blocks/music.rs

music: add format_alt

---

Cargo.lock
Cargo.toml
cspell.yaml
src/blocks/time.rs
src/formatting/formatter.rs

Add basic support for non Gregorian calendars

---

src/blocks/toggle.rs

blocks/toggle: Allow customizing State when on/off

---

Cargo.toml

Only doc features that feature-gate blocks

---

src/blocks/privacy/pipewire.rs

When many pipewire nodes/links were added at the same time the entire statusbar could end up freezing.
Fixes #2013
@kevenwyld can you verify this fix?

privacy[pipewire]: Fix status bar freezing

---

src/blocks/privacy/v4l.rs

@tkapias can you test this out with and without the workaround that you mentioned in #2006 in place?
@freswa can you test this out too?

Change device scan method for v4l privacy driver

---

src/blocks/sound.rs

blocks/sound: add format_alt

---

src/blocks/sound.rs
src/blocks/sound/pulseaudio.rs

sound: fix form_factor for pipewire

---

src/blocks/focused_window/wlr_toplevel_management.rs

It is not necessary at the moment, but may cause issues is the future.

focused_window: make get_info cancel-safe

---

src/blocks/battery.rs

block[battery]: give priority to charging over empty

---

src/formatting.rs
src/formatting/formatter.rs
src/formatting/formatter/tally.rs

I also considered calling this the rods formatter since the counting rods aren't really tally marks... Thoughts?

Add tally formatter

---

src/blocks/custom.rs

block[custom]: detect file delete/move events

---

src/blocks.rs
src/click.rs

Add support for wheel left and right clicks

---

cspell.yaml
src/blocks/packages.rs
src/blocks/packages/xbps.rs

Implements #2135 and updates docs to match.

Add xbps package manager to `packages` block

---

src/formatting.rs
src/formatting/formatter.rs
src/formatting/formatter/bar.rs
src/formatting/formatter/datetime.rs
src/formatting/formatter/duration.rs
src/formatting/formatter/eng.rs
src/formatting/formatter/str.rs
src/formatting/formatter/tally.rs
src/formatting/parse.rs

Formatting: treat key as a shortcut for key:true

---

src/blocks/music.rs
src/blocks/nvidia_gpu.rs

Document widgets in music and nvidia_gpu blocks
