greshake/i3status-rust

src/blocks/temperature.rs, src/util.rs
One of my sensors seems to not be working and gives -128 as the input.. that is obviously wrong but it crashes the program. So, I made it ignore any issues with the number parsing in the temperature. Maybe an error should be raised somewhere for awareness but it shouldn't kill everything.
=> fix bar crash if a temperature sensor gives a negative value

src/blocks/cpu.rs
In that case, the idle time will not increase between samples, so
using && would result in displaying 0% CPU usage.
=> Fix calculation of CPU usage for the case where it is 100%.

src/blocks/xrandr.rs
For primary screen xrandr puts this information ahead of the resolution info, so in this case we have to use the next word of the parsed line ^^"
=> Resolution parsing fix for primary screen

Cargo.toml, README.md, src/block.rs, src/blocks/battery.rs, src/blocks/cpu.rs, src/blocks/custom.rs, src/blocks/disk_space.rs, src/blocks/focused_window.rs, src/blocks/load.rs, src/blocks/memory.rs, src/blocks/music.rs, src/blocks/sound.rs, src/blocks/temperature.rs, src/blocks/template.rs, src/blocks/toggle.rs, src/blocks/xrandr.rs, src/input.rs, src/main.rs
This PR does two things:
* Rename `I3barEvent` to `I3BarEvent` to be consistent with the capitalization of `I3BarWidget`.
* Change the type of `I3BarEvent::button` from `u64` to an enum `MouseButton` which makes matching in an event a lot easier and a lot more readable.
This has been achieved through:
* updating serde to 1.0 (not strictly required),
* removing the `Serialize` derive from `I3BarEvent` (since we only go the one direction anyway),
* implementing a custom deserializer for the `I3BarEvent::button` field.
This is related to #36 and probably supersedes it. (cc @Drogglbecher @greshake)
=> Cleanup i3barevent, introduce `enum MouseButton`

src/blocks/pacman.rs
Simple addition to the pacman block: update the package count on a left click. (This does not conflict with the changes in #37).
=> Update pacman update count on `click`

README.md, example_config.toml, example_icon.toml, example_theme.toml, src/block.rs, src/blocks/battery.rs, src/blocks/cpu.rs, src/blocks/custom.rs, src/blocks/disk_space.rs, src/blocks/focused_window.rs, src/blocks/load.rs, src/blocks/memory.rs, src/blocks/mod.rs, src/blocks/music.rs, src/blocks/pacman.rs, src/blocks/sound.rs, src/blocks/temperature.rs, src/blocks/template.rs, src/blocks/time.rs, src/blocks/toggle.rs, src/blocks/xrandr.rs, src/de.rs, src/util.rs
Building on what I mentioned in #41, this PR implements deserialization of block configs into type-safe structs.
* [Added](https://github.com/pitkley/i3status-rust/blob/d9165b1f4ab6861ef22f3511cc012871dc69fc7c/src/block.rs#L25-L29) `trait ConfigBlock: Block` which holds a blocks config in its associated type `Config`
* Added a configuration-struct to every block
* [Deserialize](https://github.com/pitkley/i3status-rust/blob/d9165b1f4ab6861ef22f3511cc012871dc69fc7c/src/blocks/mod.rs#L43-L48) a `toml::Value` into a block's associated config type on creation
* [Added](https://github.com/pitkley/i3status-rust/blob/d9165b1f4ab6861ef22f3511cc012871dc69fc7c/src/de.rs#L11-L54) deserialization helper for durations (used for intervals).
This deserializes from either an integer, a float or a map: …
=> Deserialize blocks configs into structs

README.md
=> change `content` to `command` to match the config

README.md, src/block.rs, src/blocks/battery.rs, src/blocks/cpu.rs, src/blocks/custom.rs, src/blocks/disk_space.rs, src/blocks/focused_window.rs, src/blocks/load.rs, src/blocks/memory.rs, src/blocks/mod.rs, src/blocks/music.rs, src/blocks/pacman.rs, src/blocks/sound.rs, src/blocks/temperature.rs, src/blocks/template.rs, src/blocks/time.rs, src/blocks/toggle.rs, src/blocks/xrandr.rs, src/config.rs, src/errors.rs, src/main.rs, src/scheduler.rs, src/util.rs, src/widgets/button.rs, src/widgets/rotatingtext.rs, src/widgets/text.rs
(Regarding #42, cc @greshake @jheyens.)
So, this turned out to be a pretty big PR, given that almost everything had to be touched to support the `Result` type and the associated error-handling.
I'll try to summary the biggest changes/additions to maybe ease the burden a bit.
* `src/errors.rs`
* Added supporting code for error handling. This includes:
* An `enum Error` containing two types of errors: `BlockError` and `InternalError`
* A custom `Result` type which allows omitting of our `Error`
* Two trait extensions (`ResultExt`, `OptionExt`) which add:
```rust
fn block_error(self, block: &str, message: &str) -> Result<T>;
fn internal_error(self, block: &str, message: &str) -> Result<T>;
```
to both `Option` and `Result`, allowing easy error handling.
* An implementation for …
=> Implement error handling

README.md, src/blocks/cpu.rs
This makes the info/warning/critical thresholds configurable for the CPU block
=> Add additional options for CPU block

src/blocks/speedtest.rs
Or we could just give them different names so that they are different icons? Not sure which way we want to go, but the code should've had them being the same
=> fix speedtest net-down/up icons

src/util.rs
This means our minimum Rust version is 1.19
=> remove `eprintln!` macro due to it being on stable 1.19

src/blocks/battery.rs
I have a device with a battery named max170xx_battery, so the device config being number wasn't working. Changed it to a string to allow for different battery names. Since the documentation is moved to the wiki will need to update that separately.
=> change battery device config to string

example_config.toml, src/blocks/disk_space.rs
Defaults to previous values.
Should read "warning" and "alert" from config, alert being "Critical".
=> Adding Config options for 'alert' and 'warning' thresholds.

Cargo.toml, src/blocks/backlight.rs, src/blocks/mod.rs, src/icons.rs, src/main.rs
This PR adds a `backlight` block that shows brightness information for a given display device. It does duplicate some aspects of the `xrandr` block, but has two important advantages:
1. It reads the `sysfs` files directly instead of using an external command (like `xrandr`), which means it works on Wayland, and addresses #92; and
2. It uses `inotify` (on a separate thread) to update the block whenever the display brightness is changed, instead of updating at a set interval.
This approach does mean adding the `inotify` crate as a dependency, and it will only work on Linux. I haven't carefully profiled the block for performance issues, but it doesn't look all that suspicious in `htop`.
I've also run `cargo fmt` on the main file, for what it's worth.
=> Add a simple Backlight (brightness) block

src/blocks/sound.rs
It was not possible to increase volume if its value is greater than (100 - volume_step). For example, with volume equals 98% and volume_step equals 5% it was not possible to set volume to 100%. This commit fix the issue by increasing volume by min(volume_step, 100 - volume).
=> Fix volume increasing by a value less then step

src/blocks/net.rs
Hi,
while setting up the new `net` block, I realized that the throughput widgets are always displayed.
As I don't really want them, I added two config switches similar to `ip` and `ssid` ones defaulting to `true` so existing configurations don't change.
I tried to be as noninvasive as possible in regards to coding style, but if there is anything wrong, let me know.
I also tried to run `cargo fmt` but that generated a lot of changes in code I did not touch, so I didn't commit that.
Cheers,
Florian
=> Net block: Make tx and rx widgets optional

src/blocks/music.rs
I found myself wanting to adjust the parameters for the marquee so I figured we should allow them to be customized.
The default values have been set to the same as they are now, 10s and 0.5s (500000000ns), so this should not change anything for anyone who hasn't explicitly set the values in their config.
I'm new to Rust so I'm wondering if there is a better way to accomplish lines 144-5 & 147-8?
=> Allow customization of marquee interval and speed

blocks.md
This PR updates `blocks.md` with configuration info for the two blocks that I wrote (Backlight and Weather), and also updates the documentation of the Sound block to reflect the fact that it no longer supports the `interval` configuration option.
=> Add the Backlight and Weather blocks to the documentation, updates the Sound block documentation

README.md
32bit support was removed from which probably broke the i686 url.
=> readme: fix link to powerline font package in arch repos.

blocks.md
Related to discussion in #87, this PR rearranges and cleans up the documentation in the `blocks.md` file. The changes are actually much smaller than the diff makes it appear -- I have not added or changed much content at all.
Unless there is a strident objection that I have not forseen, I'll merge this in the next few days.
=> Alphabetize block documentation, add a TOC & standardize block formatting

blocks.md, src/blocks/battery.rs
Example:
````       show = "percentage"````
Possible values: "both", "time", "percentage".
Default: "both".
Closes #138
=> Battery: implement "show" config option to display percentage, time until (dis)charged or both.

blocks.md, src/blocks/backlight.rs, src/blocks/mod.rs, src/main.rs
This PR adds support for setting the backlight. Since it uses `sysfs`, the binary must have appropriate permissions. This should close #92.
In light of discussion in e.g. #145, scrolling will silently fail instead of crashing the block.
~~I am waiting on #135 to merge before documenting the new `step_width` parameter.~~
This PR also documents the new `step_width` parameter, the process of writing a `udev` rule to fix permissions issues, and, in general, improves internal documentation of the Backlight block.
=> Allow modifying the backlight using the mouse wheel, via sysfs

Cargo.lock
This is a bit annoying when working with branches and always having to manually revert these change in order to get a clean repo.
=> lockfile: commit changes that cargo would do to Cargo.lock every time when building something.

blocks.md, src/blocks/battery.rs, src/blocks/lib.rs, src/blocks/mod.rs, src/blocks/uptime.rs
The block will display system uptime. To save space it will only display the 2 biggest units, so weeks and days or days and hours, or hours and minutes or minutes and seconds.
=> uptime: add uptime block

src/blocks/battery.rs
read_file takes a block name that wasn't supplied
=> fix build fail on latest

src/blocks/sound.rs
unneeded parenthesis became a warning, thus making nightly fail to build
=> fix nightly breakage

blocks.md, src/blocks/custom.rs, src/blocks/sound.rs
This implements the feature requested in #158. If `$SHELL` was not set, we'll fall back to `sh`.
=> Send custom commands to $SHELL

blocks.md, src/blocks/temperature.rs
This adds an optional `format` field to the `temperature` block.
The default format remains the same as before, so it should be fully backwards compatible. The format code was borrowed from the `load` block implementation.
The goal was to allow more compact temperature strings like:
`format = "{min}~{max}°"`
(particularly since I don't care much about the average.)
I'm a beginner rustacean, so please excuse any code faux pas. Feedback is welcome. I am particularly unsure if there is a better way to get the min/max/avg in one pass (instead of 3).
=> blocks/temperature: Add format field

src/blocks/battery.rs
Didn't see any compiler warning with stable.
=> battery block: remove assignment and comment regarding rust 1.20, rust 1.25 is stabel now

blocks.md, src/blocks/memory.rs
IMO knowing that "33%" of memory is in use is enough and knowing that "33.42%" memory is used does not add that much value so I added integer-variants of percentage formats. ````{MAp}```` gets an additional ````{MApi}```` format, etc...
=> memory: add format variants of precentages as integers (without decimal points).

src/blocks/backlight.rs
Brightness is already capped at 100% so, so we can refactor
if brightness <= 100% { increase(); }
to
if brightness  < 100% { increase(); }
=> Backlight don't try to increase brightness beyond 100%, fix clippy warnings

src/blocks/temperature.rs
This is a personal annoyance, so feel free to close if the 'works with any click' functionality is desired. I could also see it being a left or right click thing, I could make that change... I just don't want it going off on scrolling.
=> Make temperature block only switch on left clicks

src/widgets/rotatingtext.rs
Similar to the problem reported in #27, which was fixed in f91a3d4, I saw this
error:
```
thread 'main' panicked at 'other was less than the current instant', libstd/sys/unix/time.rs:292:17
```
(sorry, no backtrace)
Since I am using the music block with text rotation, I am best-guessing that the
error is caused by the Instant subtraction in rotatingtext widget.
=> Fix panick when subtracting "now" Instant

src/blocks/pacman.rs
Tested this on either side of the pacman 5.1 update, the `pacman -Qu` command prints the same number of lines in both earlier and later versions.
=> Fixes #190 (underflow causing 2**64-1 update count)

blocks.md, src/blocks/disk_space.rs
Added implementation to the two missing info_types, `used` and `total`. Also there's a possibility to show a percentage which value depends on the info_type used. The default value for this is false.
With `free` it would show: `<free> (<free_percent>%)`
With `total`: `<used>/<total> (<used_precent>%)`
=> Added total and used info_types, and option to show percentage to disk_space block

Cargo.lock, Cargo.toml, blocks.md, src/blocks/mail.rs, src/blocks/maildir.rs, src/blocks/mod.rs, src/icons.rs, src/main.rs
Adds a block which displays the number of unread mails in configured inboxes. Currently only supports maildir format. It has pretty minimal functionality but might be useful to some users.
=> Add mail block

Cargo.lock, Cargo.toml, blocks.md, src/blocks/time.rs, src/de.rs, src/main.rs
For your consideration :)
**EDIT** I should probably give my use case:
I have this in my config (with the PR branch)
```toml
[[block]]
block = "time"
interval = 5
format = "%a %y-%m-%d %R"
[[block]]
block = "time"
interval = 5
timezone = "US/Pacific"
format = "Pacific: %R"
```
I'm from UK, and I want to know if I can hassle ppl in SF etc. :P
=> Implement `timezone` option for `time`.

src/themes.rs
When i recently recompiled i3 to its newest version i noticed the alternating colors of the slick theme not working correctly.
So i looked at the code and noticed that this was implemented very weirdly. The slick theme did not use the alternating tint, which is meant to be used for this, but rather used a (probably) non-intentional behavior of the tinting, in that it removes the fourth color channel (alpha?). This way, the alternating blocks did not have a fourth channel while every other block had one. Now my new version of i3 apparently does not display this fourth channel anymore, which made all the blocks have the same background color.
This change makes the slick theme use the tint. This also inverts the light and dark blocks compared to the previous version, which is not avoidable …
=> Fix alternating colors in slick theme

src/util.rs
This commit introduces an alpha channel to the current color arithmetic. That allows for a completely transparent background.
=> Add alpha channel to color utils.

src/blocks/memory.rs
`{Mp}` and `{Sp`} don't exist, use `{MUp`} and `{SUp}` instead.
Otherwise, panics with default format strings:
```
thread 'main' panicked at 'Unknown placeholder in format string: {Sp}', libcore/option.rs:914:5
stack backtrace:
0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
1: std::sys_common::backtrace::print
2: std::panicking::default_hook::{{closure}}
3: std::panicking::default_hook
4: std::panicking::rust_panic_with_hook
5: std::panicking::begin_panic_fmt
6: rust_begin_unwind
7: core::panicking::panic_fmt
8: core::option::expect_failed
9: i3status_rs::util::FormatTemplate::render
10: i3status_rs::util::FormatTemplate::render
11: i3status_rs::util::FormatTemplate::render
12: i3status_rs::util::FormatTemplate::render
13: i3status_rs::util::FormatTemplate::render
14: …
```
=> memory block: fix default format strings

src/blocks/memory.rs
This commit adds zero-padding to the percent values of the `memory` block. On my system for example, memory usage is always around `10%`. This leads to the memory block changing from one digit to two digits and vice-versa quite frequently.
I'd like to have less movement in my status bar, while keeping the values recent. The idea was to pad single-digit values with `0` in front as done in the `cpu` block. We could also pad using space.
=> Add padding to percent values of memory block.

blocks.md, src/blocks/battery.rs
I added the battery power consumption, but there are some things which needs discussion:
- Adding new values to the `ShowType`-enum for all variants doesn't feel right (see https://github.com/SWW13/i3status-rust/tree/battery_consumption2). I switched to an `Vec` for now.
- I'd love to have an format string for more customization, but that involves adding some sort of template engine and would require some more refactoring. Any plans for generic format solution yet?
```toml
[[block]]
block = "battery"
interval = 10
show = ["time", "percentage", "watt"]
```
=> Add power consumption (watt)

src/util.rs
By using [pango markup](https://i3wm.org/docs/i3bar-protocol.html) we can set the font type, size, etc individually just for the separator block, which can be useful in debugging/fixing font issues or just in terms of customisation.
eg in config.toml:
```
[theme.overrides]
separator = "<span font='FontJustForSeparator 12'></span>"
```
=> Allow use of pango markup in separator

src/widgets/rotatingtext.rs
Currently the minimum size of the block is hardcoded to 240 pixels for reasons unknown.
This leads to issues such as #223 with the music block.
Proposed changes:
- set `min_width` based on the user provided `width` value
- `min_width` should be set by characters (by passing a string) instead of by pixels
EDIT:
**1) Fixed the max_width setting for the widget**
Before (latest i3status-git, max_width set to 10 yet block size is large)
After (this PR):
**2) Fixed the 'jitter' during scrolling:**
Before (latest i3status-git):
After (this PR):
=> Fix rotating text widget width

blocks.md
The internal link 'maildir' has duplicated in the page
=> Removed duplicated Maildir link

Cargo.toml, README.md, src/main.rs
I've moved the block profiling support behind a cargo feature flag, because I believe it is little-used by anyone other than the occasional block author. I'll note that the changes I made to the code are quite crude -- perhaps in the future profiling should move to its own file.
There are some nice side effects of this change. At the moment we require the `cpuprofiler` and `progress` crates just for this feature, so as a result we're down at least 5 or so dependencies with this move. For reasons I'm not entirely sure I understand they remain in the `.lock` file, but I don't think they are used. This should also prevent surprises for users, as seen in #265.
=> Moves block profiling (and its dependencies) behind a cargo feature

Cargo.lock, Cargo.toml, blocks.md, src/blocks/sound.rs, src/main.rs
I started working on PulseAudio support (#20).
Currently the connection to the PulseAudio server works. Retrieving the current state will require callbacks as the PulseAudio library doesn't offer synchronous calls. Besides getting the callbacks to work the whole sound block should be refactored to work with different audio systems.
Current State:
=> PulseAudio Support

src/input.rs
Previously, if the separating comma was at the end of an input buffer, `serde_json::from_str(...)` would return `Err` and the program would panic. The same would happen if the input read hit `EOF`. The former issue was surfaced by running in the latest swaybar (compiled from git), and the latter while debugging the former.
With my changes, only what's between the first open and last close curly brace is sent to Serde, so both problems are fixed. We also don't need to special-case the initial `[` anymore.
=> Fix parsing of input JSON from new sway

src/blocks/custom.rs, src/blocks/toggle.rs
With the custom block a user can specify a custom command for a block.
By default it is evaluated by `sh`. The `on_click` command is however
evaluated by `$SHELL` if it's set. That behaviour should also be used
for `command` because `sh` is very limited and the user expects the
behaviour to be the same as their default shell.
This commit checks if `$SHELL` is set and uses this for all user
specified commands in the `custom` and `toggle` blocks.
=> Use SHELL env variable for custom and toggle block

blocks.md, src/blocks/temperature.rs
It’s pretty handy to adapt the threshold from one state to another to
your own hardware.
This is also a feature mentioned as missing in `blocks.md`.
=> Configurable threshold in temperature block

blocks.md, src/blocks/toggle.rs, src/widgets/button.rs
Allow the user to customize the toggle button icon so that the icon can
represent what the various toggle blocks are doing instead of having to
rely on labels.
By default, the behaviour remains the same and backwards-compatible with older configs.
I currently have multiple toggles in my status bar and they're taking up a lot of space for both the toggle icon and the label, so this allows for many compact toggles without labels.
Here's an example of one I'm using for toggling redshift:
```toml
[[block]]
block = "toggle"
command_state = "systemctl --user -q is-active redshift && echo on"
command_on = "systemctl --user start redshift"
command_off = "systemctl --user stop redshift"
icon_on = "backlight_empty"
icon_off = "backlight_full"
interval = 60
```
=> blocks/toggle: Add icon overrides, make text optional

src/themes.rs
I'm a fan of light themes :) If there's `solarized-dark` there should be `solarized-light`.
Also adds comments to the existing solarized-dark theme to identify
which solarized colors the hex codes represent.
=> Add solarized-light theme

src/blocks/weather.rs
closes #321 
```
json.wind.deg = 220.504;
json.wind.speed = 1.61;
```
=> wind degrees as float, wind direction round as i64

src/blocks/toggle.rs, src/input.rs
This should fix the deprecated trim_left/trim_right warnings.
=> Replace trim_left/right with trim_start/end

src/blocks/net.rs
Removes unnecessary shell instantiations, as well as silly "xyz | grep | awk" constructs.
=> blocks/net: Command cleanup

src/blocks/net.rs
SSID query that was changed in #339 was missing a `'` from the end of the command.
=> Fix SSID query in net block

src/widgets/button.rs
This enables pango markup for the button widget so that users can add colour to their `custom block` output using their shell command output (example below).
More examples (background colour, different font all in the same output):
=> Allow custom block to use pango formatting

blocks.md, src/blocks/battery.rs
I have a laptop with two batteries. I am not interested in the charge and time remaining of the individual batteries, but would rather see aggregate values. In particular, how long do I have until both are empty?
UPower supports this out of the box, via the concept of a DisplayDevice. From what I understand, this is basically a logical power supply representing all currently relevant power supplies. From the UPower documentation:
> [...] The "display device" [is] a composite device that represents the status icon to show in desktop environments.
For more information see https://upower.freedesktop.org/docs/UPower.html#UPower.GetDisplayDevice.
The current battery block does not allow using the DisplayDevice, because of how the D-Bus path for the battery is constructed. For the device …
=> Add support for UPower's DisplayDevice.

src/blocks/battery.rs
This is another small enhancement for the battery block with `upower = true`.
For a `PowerSupplyDevice`, the method `time_remaining` returns the time until the battery is empty if it is currently being drained, and it returns the time until the battery is full if it is currently being charged.
For a `UpowerDevice`, the method `time_remaining` always returns the time until the battery is empty, even when it is charging.
This PR changes the behavior of the `UpowerDevice` to match the `PowerSupplyDevice` w.r.t. the `time_remaining` method.
On a related note, how about changing the method `fn BatteryDevice::status(&self) -> Result<String>;` to return an enum `BatteryStatus` or so?
=> blocks/battery: When charging, show remaining time with UPower.

blocks.md, src/blocks/bluetooth.rs, src/blocks/mod.rs, src/icons.rs
This PR adds a new block and the relevant documentation. I'm using the D-Bus API, so it should be extremely light on resources. No new dependencies, either.
(I am indebted to [this blog post](http://smartspacestuff.blogspot.com/2016/02/i-got-figurin-out-dbus-bluez.html) for figuring out some aspects of the D-Bus API.)
At the moment, the block recognizes headphones, keyboards, mice, and joysticks and chooses an appropriate icon. If the device supports the `org.bluez.Battery1` interface, the block will also report the battery level.
Note that since I don't actually own a device that supports the battery interface, I'm not actually sure that it works -- any testers would be much appreciated.
Otherwise, this block doesn't do much at the moment. It is possible that we could add e.g. …
=> Add a block for Bluetooth devices

src/blocks/sound.rs, src/blocks/time.rs, src/main.rs, src/subprocess.rs
Spawning a command without waiting for it leaves behind a zombie process. This pull request waits for the spawned commands.
The time and sound blocks use the same code to spawn a child process, so I moved this code to a new module `subprocess.rs`.
If spawning the child failed, an error is returned.
Fixes #355.
=> block/time: Clean up zombie processes.

src/blocks/net.rs
=> blocks/net: Prevent crash of tun block

blocks.md, src/blocks/battery.rs
This is the first stab at a change I'd like to make across the codebase. For blocks that have more than one implementation/backend (`battery`, `sound`, `net` at some point), I'd like to introduce a consistently-named `driver` configuration option, similar to how we have the `format` and `interval` options wherever appropriate. The `sound` block already has this.
For the Battery block, this means replacing `upower = true|false` with `driver = "upower"|"sysfs"`. The old `upower` option is now deprecated, but will continue to work for the foreseeable future.
=> Replaces the "upower" config option with "driver" in the Battery block

src/blocks/net.rs
While being connected to an SSID containing whitespace, I noticed that the current method only shows the first word of the SSID. Here's a more universal solution (discussion welcome on a better command accomplishing the same goal)
=> blocks/net: parse SSID containing whitespace correctly

src/blocks/net.rs
When IP aliasing is configured on the selected NIC, 'ip' will print
each address on separate line. If the lines are not joined, it results
in being unreadable in the status line.
Closes #386
=> blocks/net: join all IP addresses of an interface in one line

blocks.md, src/blocks/sound.rs
The sound block doesn't show the volume when it's muted. This commit
adds a config option to enable just that.
It is useful to see how high the volume is turned up before unmuting.
This also allows you to adjust the volume while muted and then unmute at
the right volume.
=> sound: Add config show_volume_when_muted

src/util.rs
This tells the user which file is missing e.g. in case the config file
is missing. See #364.
=> Make the "missing config" error more verbose

blocks.md, src/blocks/cpu.rs
As discussed in #379, this pull request adds a `format` key to the cpu block, and removes the `frequency` key. The format key can have the placeholders barchart, utilization and frequency.
The default of the format key is currently `{barchart} {utilization}% {frequency}GHz`.
The barchart displays UTF8 block characters for up to 31 distinct CPU cores, each of which has 8 different states ('▁', '▂', '▃', '▄', '▅', '▆', '▇', '█').
Result:
=> Add CPU barchart (ref #379)

blocks.md, src/blocks/maildir.rs
This PR adds two enhancement to the maildir block: 
1. It lets you choose whether to count the `new`, `cur`, or both folders of the maildir(s)
2. It lets you opt out of the icon.
I'm shooting for a pair of blocks that look like this: " :email: 1 | 10 ", where the first number is the unread mails (using the `new` option), and the other is all the mails in that folder (using the `all` option). Helps me go for inbox zero. Note how there's no mail icon on the second block.
I chose defaults that preserve the existing behavior of the maildir block, so these features are totally opt-in.
=> Maildir enhancements

blocks.md, src/blocks/music.rs, src/widgets/rotatingtext.rs
This implementation was what I reached when playing around with the codebase to work out how I could do this; I'm more than happy to throw this away if we reach a different conclusion on what we want the interface to look like.
Fixes #328
=> blocks/music.rs: Support on_collapsed_click configuration

blocks.md, src/blocks/weather.rs
Adds functionality requested from issue #320.
To use, leave the weather block's `service.api_key` and/or `service.city_id`
blank, and set them instead with the `OPENWEATHERMAP_API_KEY` and
`OPENWEATHERMAP_CITY_ID` environment variables.
Implemented by making `api_key` and `city_id` `Option<_>`'s, and
providing `serde` with a default function, which tries to get the members
instead from `std::env`. Then just adding another match branch in
`Weather::update_weather` to handle the case when the members are `None`
and return a useful error.
=> Make Weather API Key and City Id Configurable with Environment Variables

src/blocks/weather.rs
This pull requests introduces changes to the weather block.
It takes the fact into account that some fields might not be present in the response of the OpenWeatherMap API (see issue #395). Specifically, it provides default values for the fields:
* speed (by default 0.0)
* deg (converted to an Option, displayed as the wind direction if Some(f64) or "-" if None)
Additionally, the pull request suggests some code changes in order to to reduce the amount of code duplication by abstracting the `malformed json` error into its own function, and by using a combination of  built-in operators on `Option`s and `Result`s and the `?` (try) operator.
=> Weather Block: Provide default value for missing wind fields, fixes #395

blocks.md, src/blocks/docker.rs, src/blocks/mod.rs, src/icons.rs
This PR adds a `docker` block which displays current counts of containers on the local docker host.
It works by calling the [system information](https://docs.docker.com/engine/api/v1.40/#operation/SystemInfo) through the local docker socket using `curl`.
Unfortunately I did not find a way to easily make this call using an in process HTTP client because of the unix socket. If there is any better solution, feel free to suggest it ^^.
Add the following snippet to your status bar, and restart your bar.
```
[[block]]
block = "docker"
format = "{running}"
```
And here's a screenshot of  the block running on my setup :tada:.
=> Add a docker block

blocks.md, src/blocks/net.rs
Hi! I wanted to see the Wifi signal strength in the status bar, and saw there was an open issue with some hints to do it. Turns out that `iw` provides this information too, so we can parse its output to figure it out. It's a bit inefficient because we may call iw several times to grep for some of its information, but I think it's fine since it doesn't happen a lot.
I've reused the formulas hinted at in the issue, and I can confirm they coincide with the results provided by the original i3status bar on my machine.
=> Fixes #387: Display WiFi signal strength in the net block

src/blocks/battery.rs
=> Blocks/battery: handle devices with no "battery" prefix in UPower

Cargo.lock, Cargo.toml
`regex` 1.3.0 allows for shrinking the dependency tree by disabling crate features. As far as I can tell we are only using the regex crate for some simple ASCII strings so we do not need the Unicode tables, thus we can safely disable those crate features to reduce our dependencies:
Before
After
(graphs generated with `cargo deps | dot -Tpng > graph.png`)
Due to `parse-zoneinfo` the dependencies have not completely gone away but if `parse-zoneinfo` updates too then the regex 0.2 dependencies should go away too.
=> Reduce dependencies

rustfmt.toml
Running `cargo fmt` or `rustfmt` gives :
> Warning: Unknown configuration option `write_mode`.
It is not listed as an option in the (Rust 2018 Edition) [rustfmt docs](https://rust-lang.github.io/rustfmt/ ) and it looks like it has been deprecated according to issues such as rust-lang/cargo#5545.
My env: rustc 1.37.0
=> Remove depecrated configuration option

src/blocks/ibus.rs
After #434 was merged, [this](https://github.com/greshake/i3status-rust/blob/f90bc9874d060a24276c2808275f4068d30ba47b/src/blocks/ibus.rs#L185) line started to cause a panic when using the `ibus` block. 
Adding the `unicode-perl` feature to the crate resolves this issue.
```
> i3status-rs  ~/.config/i3status-rust/config.toml
{"version": 1, "click_events": true}
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Syntax(
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
regex parse error:
^:(\d{1})$
^^
error: Unicode-aware Perl class not found (make sure the unicode-perl feature is enabled)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
)', src/libcore/result.rs:999:5
note: run with `RUST_BACKTRACE=1` …
```
=> Fixes a panic in the iBus block due to the use of Perl regex features

src/blocks/net.rs
This is only basic support, because wireguard device can be named at will:
```
[root@tokk wireguard]# ip -4 a s
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
inet 127.0.0.1/8 scope host lo
valid_lft forever preferred_lft forever
2: enp6s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
inet 192.168.2.3/24 brd 192.168.2.255 scope global noprefixroute enp6s0
valid_lft forever preferred_lft forever
33: vpnwireguarg0: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 qdisc noqueue state UNKNOWN group default qlen 1000
inet 10.0.0.3/24 scope global vpnwireguarg0
valid_lft forever preferred_lft forever
[root@tokk wireguard]# grep wireguard /sys/class/net/vpnwireguarg0/uevent
DEVTYPE=wireguard
```
And the only way …
=> Add basic support for wireguard devices

src/blocks/keyboard_layout.rs
A new "driver" option is added: kbddbus, if kbdd (https://github.com/qnikst/kbdd, also in AUR and Debian) is running, the new keyboard layout driver will observe dbus for keyboard layout changes (which can be triggered by the user or by changing the current window focus upon which kbdd will restore the previous layout for the new window).
kbdd provides layout as integer through dbus which correspond to one in the output from setxkmap -query, so after the index is obiained the current layout is extracted from setxkbmap.
Test/verify:
in .i3/config:
exec_always setxkbmap -layout us,de -option "grp:alt_shift_toggle"
exec_always pkill kbdd; kbdd
modify keyboard_layout block configuration with:
driver = "kbddbus"
I'm fairly new to rust, but I like it, and i3status-rs seems to be my favorite, so …
=> Keyboard layout kbdd - per window keyboard layout

src/blocks/disk_space.rs
These were broken by #449, which naively fixed armv6 builds.
This commit should now work on all platforms.
It wraps all return values of statvfs from the nix crate in
`as u64`, which means that the platform specific data type
(which might be u32 instead) is always converted to u64 when
necessary. Before this, only values which were known to cause
an issue were converted.
=> fix builds on armv7 and i686

src/blocks/keyboard_layout.rs
I'm mostly using i3status-rust on my laptop and I've noticed that after undocking the laptop sometimes (not always) the output of setxkmap is changed from:
>...
> layout:     us,bg
> variant:    ,bas_phonetic
> 
to
>...
> layout:     us,bg:bas_phonetic
and the width of the indicator becomes way too big when switching between the layouts because it includes and the variant, so I've stripped that from the output, since originally it was not supposed to be there.
=> strip keyboard variant from setxkbmap output to preserve space

CONTRIBUTING.md
Since the codebase is now formatted as of #457, CONTRIBUTING.md has become out of date.  This PR is an attempt to bring it up to speed with the current state of the project.
Any edits from maintainers are most welcome. I just decided to open a PR instead of an issue since it only takes an extra minute and is usually more effective.
=> Update contributing guidelines after #457

blocks.md
Just noticed that #344 adds an option I was searching for and couldn't find in the docs. :smiley_cat: 
Copied over from src/blocks/net.rs
=> Add missing documentation for hide_missing and hide_inactive to net

src/blocks/sound.rs
This tries to fix the second issue mentioned in https://github.com/greshake/i3status-rust/issues/405#issuecomment-565485933
From limited testing the panic seems to have gone away with this change.
=> Fix panic in sound block

themes.md
"netw-wireless" is "net-wireless"
=> Typo for override network wireless icon document

Cargo.lock, Cargo.toml
Disable optional dependencies allows us to get rid of 6 dependencies from our project:
- ansi_term
- atty
- strsim
- vec_map
- redox_termios
- termion
Reason we can disable these optional dependencies:
- "suggestions": Turns on the Did you mean '--myoption'? feature for when users make typos.
**Reason**: Not needed for our case as `i3status-rs` isn't a CLI app that we are manually invoking all the time. It's set once in our i3/sway config and left alone. Also, our only CLI flags are `exit-on-error`, `help` and `version`.
- "color": Turns on colored error messages. This feature only works on non-Windows OSs. 
**Reason**: As per above.
- "vec_map": Use VecMap internally instead of a BTreeMap. This feature provides a slight performance improvement.
**Reason**: Performance seems about the …
=> Remove 6 optional dependencies used by `clap`

Cargo.lock, Cargo.toml, src/main.rs, src/widgets/graph.rs
Removes the following:
- num-bigint
- num-complex
- num-iter
- num-rational
- rustc-serialize
The only place we use the `num` crate is in the graph widget, however it only uses `clamp` and `ToPrimitive` which can be provided by just the `num-traits` subcrate.
Dependency graphs:
Before:
After:
Future work: Remove this dependency all together as writing a clamp function is only a few lines, and can probably work around the need for ToPrimitive as well.
=> Remove 5 dependencies by replacing `num` with `num-traits`

blocks.md, src/blocks/net.rs
corrections per github PR suggestions
* rename default_bits to use_bits for clarity
* fix display bug when units are bits, so big
B and little b are respected
* add documentation to blocks.md for new flag
=> add ability to specifiy between bits and bytes for net block

blocks.md, src/blocks/pacman.rs
This PR expands the customization potential for the pacman block by allowing specification of custom format strings.  See the updated documentation in `blocks.md` for details
=> Allow custom formatting of the pacman block

src/blocks/backlight.rs, src/blocks/nvidia_gpu.rs, src/blocks/sound.rs, src/blocks/xrandr.rs, src/config.rs, src/input.rs
Prior to this `NaturalScrolling` option configured on XServer's input devices would lead to inverted behavior. The new functionality is enabled via a top level `scrolling = "natural"` line in the config file. The default is `scrolling = "reverse"`.
=> Allow  for natural scrolling.

src/blocks/backlight.rs
After not getting sysfs access to work, even with the udev rule mentioned in the documentation, I investigated how other applications/desktops are controlling the backlight brightness.
As it turns out, on systems governed by systemd-logind (or elogind), the correct way [according to the systemd developers](https://github.com/systemd/systemd/issues/14463#issuecomment-570190340) is the DBus interface of logind.
This commit uses this method as a fallback for when we cannot open the sysfs file. This works great on my system, but I'm not particularly attached to this method if you find it too surprising. If you'd rather like a configuration option to switch between two methods, I can implement that as well.
=> set backlight brightness via DBus when sysfs is inaccessible

src/blocks/custom.rs, src/blocks/notmuch.rs, src/blocks/temperature.rs, src/blocks/toggle.rs, src/de.rs
Error::description() is [deprecated](https://github.com/rust-lang/rust/blob/e0bbe7915e2b663ac84244918d6d06e0747ed33e/src/libstd/error.rs#L138) since Rust 1.41.0.
Will solve current/future build errors on 1.41+
=> Solve Error::description() deprecated errors on Rust 1.41

src/icons.rs
While investigating #290 I found loads of these errors in my sway log, about 50 a second from the looks of it:
```
2020-01-21 22:21:46 - [common/pango.c:64] pango_parse_markup ' <  ' -> error Error on line 1 char 11: “ ” is not a valid character following a “<” character; it may not begin an element name
```
I checked the output of `i3status-rust` and found the culprit to be the `prev` button for the music block.
```
{"background":"#2196f3","color":"#ffffff","full_text":" <  ","markup":"pango","name":"prev","separator":false,"separator_block_width":0}
```
Checking the [pango markup docs](https://shinmera.github.io/pango-markup/#FUNCTION%20PANGO-MARKUP%3AESCAPE-CHAR), "<" is one of four characters that may need escaping. In our case, it is being interpreted as the start of a tag block in …
=> Escape char to avoid pango_parse_markup error

src/blocks/notmuch.rs, src/main.rs
A couple that were missed in 6b602784f8758631c274c1f7013189695ad5bcb7.
Is it trivial to get our Travis CI to test our optional features as well? It doesn't seem to be doing that at the moment, just the standard build with no options.
=> Update bare trait objects

.travis.yml, src/main.rs
Add `--all-features` and `--all-targets` to make sure all code gets
compiled. This uncovered a type mismatch with the `profiling` feature
enabled, which this commit fixes as well.
=> Travis CI: Adjust to check all code

blocks.md, src/blocks/bluetooth.rs
I have a couple different bluetooth devices that I connect to at different times, and I realized that it would be a lot easier to tell them apart with labels. 
It's optional, and if included it shows up to the right of the icon and left of the connected indicator.
=> added labels to bluetooth devices

NEWS.md, blocks.md
As per the title.
Wasn't sure how to communicate the default thresholds which are set to `<u32>::max_value()` so I just put an arbitrarily large enough number which, when given this block deals with mails, should get the point across.
=> Document the optional `notmuch` block

src/subprocess.rs
If stdout from child processes is not deliberately ignored and/or
quieted via external means, it can interfere with the i3bar protocol
stream. Stdin is less dangerous, but gets closed almost immediately by
`wait()`ing.
Connect both of them to `Stdio::null()` to avoid any problems. Stderr
is safe and can remain as-is for debugging purposes.
=> Ignore stdin and stdout for `spawn_child_async`

Cargo.lock, Cargo.toml, src/main.rs
Closes #465 by adding a `--config` option flag.
If the flag is omitted then we default to reading from:
1. $XDG_CONFIG_HOME/i3status-rust/config.toml
2. $HOME/.config/i3status-rust/config.toml if XDG_CONFIG_HOME is not set.
NOTE: This is a breaking change.
For users who happen to be using a different path to the above for their config files, they will have to update their invocation of i3status-rs to use the `--config` option. 
For other users they will need to remove the argument from their i3status-rs command.
=> Read config from XDG_CONFIG_HOME by default

src/blocks/focused_window.rs
Closes #536 
It's unlikely that the IPC will go down between checking and starting the thread, so this should be fine for most cases.
A better solution would be #538 but the solution does not look trivial, so I think we should make this fix for now.
=> Add connection check before starting thread to prevent panic

blocks.md, src/blocks/load.rs
Added possibility to customize thresholds for the states in the Load block. Mostly just pasta from cpu.rs.
closes #509
=> feat(load): possible to configure thresholds

Cargo.toml
Since have been working with dependencies a lot lately this had been getting on my mind.
Had a gander at some other crates like `tokio` and they do this there too.
=> Chore: Order deps in alphabetical order

.travis.yml, man/_postface.1, man/_preface.1, man/generate.sh, man/i3status-rs.1
The final man page is currently generated from the `blocks.md` and `themes.md` files, plus a custom preface and postface. You can run `man/generate.sh` to regenerate the man page after changes to those files.
I have also added a check to Travis CI that ~will fail if~ a commit updates the block/theme documentation but does not regenerate the man page in this way, which we should probably document somewhere.
This should close #380 and supersedes #391.
=> Adds a man page

.travis.yml
This fixes #545, where the nightly builds are timing out at the cache step.
It is likely that our caches are too large and they cannot be expanded within the allowed time frame.
See:
https://travis-ci.community/t/builds-timeout-during-or-shortly-after-creating-directory-home-travis-cache-sccache/5001/2
https://gist.github.com/jkcclemens/000456ca646bd502cac0dbddcb8fa307
https://www.reddit.com/r/rust/comments/dbgril/caching_on_travis_when_building_rust_projects/
=> Clear cache for travis builds

src/blocks/pacman.rs
I think the `pacman` block is a very useful indicator to remind me if I have to update my system again or not. Nevertheless, sometimes it is useful to know if there are any critical updates which might need a restart of the system (usually the kernel). Therefore, this patch will introduce a new configuration option (`kernel_updates_are_critical` which is by default `false`) to indicate the block as critical as soon as a kernel update is available. Otherwise the block behaves as before.
=> Kernel updates in the pacman block can be marked as critical

blocks.md, src/blocks/custom.rs, src/widget.rs
This builds on the work in #165:
- support for setting the icon has been added
- non-JSON output is passed through as-is which allows us to not break users' configs (block behaves the same as now).
This allows for a more versatile `custom` block and should solve the following issues such as #331, #414 and #454 as long as the user writes a wrapper script for their commands that outputs JSON.
=> Add JSON parsing to Custom block

src/blocks/backlight.rs, src/blocks/ibus.rs, src/blocks/sound.rs
Same as #535, but for the remaining blocks with the same issue.
Solves #581
=> Fix panics for blocks without update intervals

blocks.md, src/blocks.rs, src/blocks/watson.rs, src/de.rs
This adds a simple block to display the current time tracking status for [watson](http://tailordev.github.io/Watson/).
The module does not add any dependencies and is rather simplistic.
=> Add Watson block

src/blocks/backlight.rs, src/blocks/battery.rs, src/blocks/bluetooth.rs, src/blocks/focused_window.rs, src/blocks/ibus.rs, src/blocks/keyboard_layout.rs, src/blocks/music.rs, src/blocks/networkmanager.rs, src/blocks/sound.rs, src/blocks/speedtest.rs, src/input.rs, src/subprocess.rs
This should make debugging at least a little easier/faster.
(Have been investigating a couple of different panics and this has come in handy,)
The unwraps are necessary because thread::Builder::spawn returns a Result, however the behaviour should be the same as before because thread::spawn panics on failure anyway.
=> Name threads for easier debugging

blocks.md, src/blocks/net.rs
Also fixed up a typo and made a serde default conform to other usages
=> Include use_bits in blocks examples

src/blocks/temperature.rs
On my machine (ThinkPad X1C 6th Gen, Linux 5.5.13), `sensors` shows 16
`temp*` temperatures for `thinkpad-isa`. All of those temperatures are
taken into account although most of them show 0°C.
It seems as not all sensors are supported. When trying to get the value
of a `temp*` value via `cat` in `/sys/class/hwmon/...`, I get an error
like this:
```
$ cat temp2_input
cat: temp2_input: No such device or address
```
Although those results can't be fetched and are shown as `0°C`,
the temperature block takes those into account when calculating the
average temperature. This patch ignores every input which returns `0` to
get the actual average temperature.
=> blocks/temperature: Only take supported inputs into account

src/blocks/keyboard_layout.rs
This PR add `format` argument to `keyboard_layout` block. For now, it only supports `{layout}` placeholder.
The reason for this addition is that I want to add an icon to my keyboard block, something like this:
```toml
[[block]]
block = "keyboard_layout"
driver = "localebus"
interval = 5
format = " {layout}"
```
I could have also added an icon to the keyboard block, however I prefer this approach since it is more flexible, and allow in the future support for more information in `keyboard_layout` block (like keyboard variants).
This is my first code in Rust so if there is any issues, please report it and I will try to fix it :+1: .
=> keyboard_layout: Add `format` argument

src/blocks/taskwarrior.rs
Garbage Collection is a taskwarrior configuration option that is descibed here: https://taskwarrior.org/docs/ids.html.
It should be always disabled when calling `task` from scripts. Otherwise gc will modify ID numbers of the pending tasks when we complete or delete tasks from the another script.
This will also increase the speed of update for this widget (see "Configuration" section here: https://taskwarrior.org/docs/ids.html).
=> taskwarrior: Force rc.gc=off

src/blocks/memory.rs
This fixes #285
The memory and weather blocks are the only blocks using `render` which panics instead of raising an error. All other blocks use `render_static_str` and there is even a TODO in the source saying to use it instead of `render`.
=> memory block: fix panic when wrong placeholder given

blocks.md, src/blocks/sound.rs
> Right now it just supports {volume}. Defaults to {volume}%.
Rebased from #501
=> Allow sound block to have a format string

blocks.md, src/blocks/pacman.rs
This PR adds `critical_updates_regex` field to pacman block configuration.
Pending updates matching this regular expression are displayed as critical (this a follow up of #595)
The regex showcased in pacman's block documentation has been tested:
```rust
#[test]
fn test_kernel_critical_updates_regex() {
let regex: Regex = Regex::new("(linux |linux-lts|linux-zen|linux-hardened)").unwrap();
let kernel_update = "linux x.x -> y.y";
assert!(has_critical_update(kernel_update, &regex));
let kernel_update = "linux-lts x.x -> y.y";
assert!(has_critical_update(kernel_update, &regex));
let kernel_update = "linux-zen x.x -> y.y";
assert!(has_critical_update(kernel_update, &regex));
let kernel_update = "linux-hardened x.x -> y.y";
assert!(has_critical_update(kernel_update, &regex));
let kernel_update = …
```
=> Allow pacman critical updates config using regex

src/blocks/net.rs
When using android usb tethering in Arch Linux (kernel: Linux 5.6.5-zen4-1-zen),
`operstate` file shows `unknown`. But the `carrier` file correctly shows `1`.
`ethtool` also correctly says `Link detected: yes`.
=> Use /sys/class/net/<device>/carrier instead of operstate in is_up()

blocks.md, src/blocks/net.rs
=> net block: show bitrate for wired devices

blocks.md, src/blocks/cpu.rs
This PR introduce a new config parameter for the block `cpu`: `per_core`.
When set, the block will display the metrics for each core instead of computing an average.
This work for both frequency and utilization percentage.
Closes: #603
=> Allow to display per-core CPU metrics

src/blocks/backlight.rs
As mentioned in https://github.com/greshake/i3status-rust/issues/447
Other bars do this too: https://github.com/polybar/polybar/commit/627c4ac2af477826e26d799abe790d5c3b0f5aed
=> backlight: read from actual_brightness as per kernel docs

blocks.md
* documented `warning`
* documented `alert`
* documented more allowed values for `info_type`
* documented that `Percent` is allowed for `unit`
=>  blocks.md: Aligned the 'Disk Space' block documentation with reality

blocks.md, src/blocks/toggle.rs
Resolves #167
Old behaviour: block would toggle state regardless of whether `command_on`/`command_off` exited successfully.
New behaviour: block only toggle states if `command_on`/`command_off` exited successfully (non-zero exit status).
I left `command_state` alone for now.
Future work could make change the colour of the block when command_on/off didn't run successfully, otherwise a user might think the bar is just being unresponsive.
=> toggle block: only toggle if command exited successfully

blocks.md, src/blocks/music.rs
This allows the block to be a little smarter in how it trims text to fit within
a max width. More precisely - it will trim from both the artist and the title
in proportion to their lengths, to try and show the most information possible.
Based on work done by https://github.com/jgbyrne mentioned here:
https://github.com/greshake/i3status-rust/issues/189
Resolves #189
=> music block: add smart_trim config option

src/blocks/battery.rs
Hi, I did not like the battery module displaying `0:00` most of the time. I am not sure about the space left behind, i.e. in `{percentage}% {time}`. It seems unwise to have a formatter that generates a space. which would allow doing `{percentage}%{time}` eliminating that trailing space, but looks weird in configs and leads to double spaces with existing configs.
It might be best to introduce a new formatter, but I'm not sure.
=> battery: only display remaining time when it is useful

src/blocks/battery.rs
Resolves #429 by implementing the simple approach mentioned here: https://github.com/greshake/i3status-rust/issues/429#issuecomment-626132440. This could be worked on in the future for better hysteresis.
I don't have a battery operated device to test with at the moment so would appreciate if @travankor, @GladOSkar could check this out if they have time.
=> battery block: fallback for determining power consumption

blocks.md, src/blocks/pacman.rs
cf #385 
create a minimal `status.toml` with the following content:
test legacy/deprecated {count} syntax without AUR:
```toml
[[block]]
block = "pacman"
interval = 600
format = "{count} updates available"
format_singular = "{count} update available"
format_up_to_date = "system up to date"
```
test new {pacman} syntax without AUR:
```toml
[[block]]
block = "pacman"
interval = 600
format = "{pacman} updates available"
format_singular = "{pacman} update available"
format_up_to_date = "system up to date"
```
test new {aur} syntax (AUR only) (it should error since aur_command was not supplied):
```toml
[[block]]
block = "pacman"
interval = 600
format = "{aur} updates available"
format_singular = "{aur} update available"
format_up_to_date = "system up to date"
```
test new {aur} syntax (AUR …
=> add AUR support for pacman block cf #385

.travis.yml, src/main.rs, tests/run_binary.rs, tests/testconfig1.toml
As discussed in #555 
Also added a simple config to be tested with the compiled binary. It can be run locally as well using `cargo test`, and is tested by Travis CI as well.
=> Add "one-shot" mode and add some tests

src/blocks/focused_window.rs
This can be merged once tmerr/i3ipc-rs/pull/51 has been implemented.
Solves #486
=> Add option to show marks instead of title

src/blocks/net.rs, src/widgets/button.rs
Reverts part of #650 as the escaping was being done in the wrong place.
Unilaterally escaping everything means pango formatting set by users in their config will be broken.
Instead, we need to escape on a per-block, per-item basis.
For now, the net block's SSID display has been identified a source of unintended pango formatting, so that has been escaped. There may be others, they will have to be done as discovered.
=> Fix pango escaping

src/blocks/toggle.rs
This may possibly fix #669, otherwise it's a separate bug I discovered while debugging.
=> toggle block: swallow stdout/stderr

src/blocks/toggle.rs
#648 made it so the toggle block only toggles if the respective toggle
command exited successfully. However from a user point of view there was no
feedback, so the user might think their clicks are not registering when in
they are. This PR sets the block state to Critical when a toggle command
fails in order to give visual feedback. The state is reset once clicked again
and the command succeeds, or until the next time the command_state cmd is run.
=> toggle block: set block colour if toggle command fails

src/blocks/focused_window.rs
One small fix for the new marks-related changed. Otherwise, the bar freezes when closing windows.
=> focused_window: fix freeze on closing window

src/blocks/memory.rs, src/blocks/speedtest.rs
This fixes the clippy warnings on nightly (where https://rust-lang.github.io/rust-clippy/master/index.html#match_on_vec_items) is introduced.
=> Fix nightly clippy lints

src/blocks/backlight.rs, src/blocks/focused_window.rs, src/blocks/ibus.rs, src/blocks/sound.rs, src/main.rs
This undoes the bandaid fixes that were implemented to deal with the panics that
occur when only using blocks that have no update interval (ones that use DBus etc).
Instead of kludging a dummy update interval to those blocks, the scheduler
logic is changed so that no updates are scheduled if the block has no
update_interval value set.
=> Better fix for #535 and #582

.travis.yml, src/blocks/notmuch.rs, src/main.rs
This fixes up a few more clippy lints necessary to enable clippy for all features and targets and enables the check in travis.
=> Enable clippy for all features and targets

blocks.md, src/blocks.rs, src/blocks/custom_dbus.rs
Supersede #426 
This allows you to have a custom block that updates instantly over DBus. 
For example, you might have a script that changes your sound output device.
With the standard `custom` block, you would setup the block like this:
```toml
[[block]]
block = "custom"
command = "check_current_sound_output_device"
interval = 1
```
where the command is a separate script that checks the current sound output device, and the block can only be updated up to once per second. 
However with this new block, you can add a line at the end of your script that changes your sound output device to send a message over DBus to instantly update the block:
```toml
[[block]]
block = "custom_dbus"
name = "CurrentSoundOutput"
```
and add this inside your sound output change script: `qdbus i3.status.rs …
=> Add Custom DBus block

src/blocks/cpu.rs
When the option "per_core" was true the last core
had two percent signs because one was added for each core
and another was added after the "utilization" placeholder.
When "per_core" is true the last percent sign after "utilization"
is no longer added.
=> Fix CPU format when per_core is true

blocks.md, src/blocks/weather.rs
Resolves #367 
This uses the geolocation service mentioned in https://github.com/greshake/i3status-rust/issues/367#issuecomment-489889913 to automatically change the location used for retrieving weather info
@kflak If you have some time could you please test this? It works fine for me but more QA wouldn't hurt.
=> weather block: add autolocate option

src/blocks/keyboard_layout.rs
The child process was only spawned and its output was not checked/read so its handle was kept through the whole lifetime of i3status-rust.
=> Fix #696 - zombie setxkbmap process with kbddbus keyboard layout

blocks.md, src/blocks/pomodoro.rs
I tried to use the pomodoro block with the hide mode enabled in sway, however I notice that it didn't update while the bar is not visible. I've made some fixes to the block, changed the behavior to not update a counter, now it stores the `DateTime` when the pomodoro starts.
I still have some problems calling `swaynag` or `i3-nagbar` when the bar is not visible.
=> pomodoro: store datetime instead of using ticks, add nag config

blocks.md, src/blocks.rs, src/blocks/github.rs, src/icons.rs, src/util.rs
This PR adds a `github` block which displays current count of unread notifications for an user. 
It enables to display a total count of unread notifications and also a count per "notification reasons" [see here](https://developer.github.com/v3/activity/notifications/#notification-reasons).
To support this, I had to make a change on the token regexp of the `FormatTemplate`, to make it also support tokens with a `_` or a `-` character in it (see bf71cd0).
It relies on the [Notifications API](https://developer.github.com/v3/activity/notifications/) of the Github API v3 and iterates through all the notifications pages.
Add the following snippet to your status bar, and restart your bar.
```
[[block]]
block = "github"
format = "{total}|{author}|{comment}|{mention}|{review_requested}"
```
And …
=> Add GitHub block

src/blocks/net.rs
(Mostly?) Resolves #240. 
@GladOSkar Thanks for doing the legwork on this one!
This also uncovered a calculation error with `use_bits`, which is now fixed.
Comparing the new default format (max 3 digits, minimum unit K):
```
new format: '46.8M'	 with use_bits: '0.37Gb'
cur format: '   46M'	 with use_bits: '  368M'
new format: '6.81M'	 with use_bits: '54.5Mb'
cur format: '    6M'	 with use_bits: '   48M'
new format: '0.81M'	 with use_bits: '6.51Mb'
cur format: '  813k'	 with use_bits: '    0M'
new format: '13.6K'	 with use_bits: '0.11Mb'
cur format: '   13k'	 with use_bits: '  104k'
```
In my opinion this is now way better than before. The only caveat may be when using `use_bits` as in the first example above - perhaps we should display in megabits instead of gigabits for that case. …
=> net block: improve throughput formatting

blocks.md, src/blocks/sound.rs
Adds new format qualifier `output_name` which will show the name of the sink whose volume is being reported. This is handy when you have multiple audio outputs that you switch between.
Sink names can be checked via `pactl list short sinks`, and usually look something like "alsa_output.pci-0000_00_1b.0.analog-stereo". Displaying that as-is would be clunky, so this PR also adds a "mapping" config similar to that used in the `ibus` block, where you can assign a display name for each sink.
=> sound block: allow current sink name to be shown

src/main.rs
@GChicha Can you see if this makes any difference with regards to the bar being stopped while hidden?
=> Prevent bar being stopped by using signal other than SIGSTOP

blocks.md, src/blocks.rs, src/blocks/battery.rs, src/blocks/kdeconnect.rs, src/icons.rs, src/util.rs
=> Add kdeconnect block

src/blocks/kdeconnect.rs
This would make i3status-rs crash for me, now it at least gives an error. Although maybe it would be better to wait until it can connect to the daemon? idk
=> Make sure KDE Connect properly errors when it can't connect to the daemon

README.md
Until this is published to crates.io, a cargo install --git command can be used as well.
=> Add instructions on how to install with cargo

blocks.md, src/blocks/custom_dbus.rs, src/widget.rs
This is a fairly straightforward feature for the relatively new custom_dbus block.
=> Allow setting the icon and state in custom_dbus

src/blocks/nvidia_gpu.rs
When the nvidia driver is updated and the new module hasn't been loaded, `nvidia-smi` can produce invalid output such as "Failed to initialize NVML: Driver/library version mismatch", which can cause a panic.
This adds a check to ensure the output from `nvidia-smi` contains at least 2 commas.
=> Add check for valid nvidia_smi output

src/blocks/net.rs, src/blocks/xrandr.rs
Replace calls to sed, awk, grep, etc with the regex crate where possible.
Currently, don't have access to a machine with Wi-Fi, so those calls have been left in for now.
Closes #725
=> Sed awk grep removal

src/blocks/taskwarrior.rs
The task command count the deleted tasks as pending , adding `-DELETED` to the task command give the correct count of current pending tasks
=> Fix: TaskWarrior - Don't count deleted items

.github/workflows/rust.yml
since we're running clippy afterwards anyway
=> CI: allow build with warnings

blocks.md, src/blocks/cpu.rs
I wanted this so I can easily open a terminal with `top` running when my cpu usage is high.
Note: this is my first time working with rust. I pretty much just copy pasted code from other blocks.
Took me quite a while to figure out i needed to switch from textwidget to buttonwidget, to make the "name" identifier be emitted for the cpu block, such that click events can have the corresponding name and we can link it back to the cpu block.
some basic instructions for new developers could be helpful for people like me, but otherwise great project :+1:
=> add `on_click` setting for cpu block

src/input.rs
Looks like it was accidentally added in fe517af58a5c10d7596cb7d4d6096cd7d5739052
Remove it for now as it's not particularly helpful, however can introduce a --debug flag in the future.
=> Stop printing mouse input events to stderr

src/blocks/focused_window.rs
My window block is systematically crashing after a while:
```
thread 'focused_window' panicked at 'called Result::unwrap() on an Err value: Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" }', src/blocks/focused_window.rs:81:27
```
While I'm not exactly sure what swayipc occasional errors mean, I think it is not critical enough to crash the subscribed thread. I changed that behavior to log the error in `stderr` and continue running normally. Also, it seems to show that my error might be that swayipc crate receive wrongly formatted data somewhere (?):
```
[warn] error in `window` block: missing field `instance` at line 1 column 619
```
While I was on it, I tried to replace all `unwrap` calls by at least an `except`, this doesn't change much of the behavior but I think it …
=> fix crashing thread in window block

src/blocks/net.rs
1) don't include extraneous 'SSID: ' prefix. see #814 
2) an SSID is allowed to contain any character. update regex
accordingly. in particular mine is of the form foo-1234
and my ssid was reported as 'foo'.
I'm a rust beginner so any feedback on the code is welcome.
I think more can be fixed in this block (e.g. adjusting the other regexes etc), but one small step at a time :)
=> net block: fix IW SSID regex parsing

src/blocks/net.rs
Well, it isn't the prettiest, but it does work. A simple workaround for the empty first array object in slightly older `iputils` packages.
Rust is _absolutely_ not my most comfortable language, so if there is a rust-y way to de-duplicate that code, please do not hesitate to say 'here it is, idiot' and fix it.
Thanks :D
=> Use serde_json to get IP address instead of sed

blocks.md, src/blocks/disk_space.rs
Added option to use absolute unit values
See #829 
Tested on my config:
```toml
[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GiB"
interval = 20
warning = 20.0
alert = 10.0
format = "{icon}{used}/{total} {unit} ({available}{unit} / {percentage} free) "
```
=> Use percentages for disk space alert and warning by default.

Cargo.lock, Cargo.toml, blocks.md, src/blocks.rs, src/blocks/custom.rs, src/input.rs, src/main.rs, src/signals.rs
Add a **status** field to the custom block that takes a value between 0 and 30. These correspond to SIGRTMIN+0 to SIGRTMIN+30.
This causes the block to be updated by sending the corresponding SIGRT signal to i3status-rs. This can be done via
`pkill -SIGRTMIN+1 i3status-rs` in order to send a signal to blocks listening for signal 1.
This feature allows custom blocks to not need to be updated on an interval, but instead can be updated via scripts sending a signal when they need to update.
A possible flaw is that I was not able to find a good way of pulling in the signal range dynamically from the users computer, instead the range is hard-coded to listen to signals between 34 and 64 (where this is the range on my computer).
The relevant constants can be found in **src/signals.rs**
=> Signal support

src/blocks/nvidia_gpu.rs
If someone sets `label` in their config then it is a pretty good bet that they want the bar to display that instead of the default GPU name from `nvidia-smi`.
Up until now those users would have had to click the bar after startup to get the widget to show the label, but now it will show the label first by default.
Should resolve the usecase desired by #754
=> nvidia block: if label is provided then show it first

src/blocks/bluetooth.rs
Resolves #583 (hopefully)
I don't have bluetooth to test with so will leave this undocumented until it's confirmed working.
=> bluetooth block: add option to hide block when device is disconnected

src/blocks/load.rs
Resolves #749, supersedes #748
This works on my system, but then again mine worked with the old code too.
This PR uses the same method as the `cpuinfo` crate to determine the CPU count.
=> load block: fix CPU count

blocks.md, src/blocks/custom.rs
Also fixes `on_click` to have the same behaviour as `command`, whereas previously it was set to `sh`
=> custom block: add option to set the shell used

Cargo.lock, Cargo.toml, blocks.md, src/blocks/time.rs, src/de.rs
Resolves #73 via a new config option.
test config
```toml
[[block]]
block = "time"
[[block]]
block = "time"
locale = "fr_BE"
timezone = "US/Pacific"
```
output
> {"version": 1, "click_events": true}
> [[{"background":"#000000","color":"#a9a9a9","full_text":"| ","markup":"pango","separator":false,"separator_block_width":0},{"background":"#000000","color":"#93a1a1","full_text":" **Wed 14/10 11:35** ","markup":"pango","name":"e97f48901fa4434daf67d4fbf94c0480","separator":false,"separator_block_width":0},{"background":"#000000","color":"#a9a9a9","full_text":"| ","markup":"pango","separator":false,"separator_block_width":0},{"background":"#000000FF","color":"#93A1A1FF","full_text":" **mar 13/10 19:35** ","markup":"pango","name":"a874badad8a14e6bbf1f49cc22347db9","separator":false,"separator_blo …
=> time block: support locales

Cargo.lock, Cargo.toml
Might cut a new release soon so might as well get this out of the way now.
Left dbus at 0.8 for now since it needs some intervention.
=> prepare for new release by bumping deps

src/blocks/net.rs, src/blocks/nvidia_gpu.rs, src/blocks/temperature.rs, src/widget.rs, src/widgets/button.rs, src/widgets/graph.rs, src/widgets/rotatingtext.rs, src/widgets/text.rs
I have added a spacing setting for each widget that can control the spacing.
The `Inline` setting will remove the leading space, which is very useful for sub-widget in some blocks.
The `Hidden` setting will remove both the leading space and trailing space, which is useful for hidden blocks.
To demonstrate the usage, I have also fixed the spacing for `nvidia_gpu` block.
This PR should resolve the issue #800.
=> Fix spacing for inline widgets

src/blocks/memory.rs
Most likely this was used during development but is no longer necessary.
=> memory block: remove old debug code

src/themes.rs
currently the plain theme has a weird spacing with the separator. I expect this is not intentional.
=> [theme-plain] have seperator without extra space

blocks.md, src/blocks/net.rs
Fix net block issue where both `hide_inactive` and `hide_missing` had to be enabled to ever hide the block on either case. (#891)
This PR implements the functionality as i would expect it:
- active = !exists || !up
- show full block if active
- hide block if inactive && hide_inactive || !exists && hide_missing
- otherwise, show only icon
I tested all cases and it works as described.
Does that sound correct to you, @ammgws @mvdan ?
=> Fix net block hiding issue

blocks.md, src/blocks/backlight.rs
The raw brightness values are quite useless on some hardware. Add an
option to scale the raw backlight PWM values on a power scale.
Since there is no single correct exponent even in the CIELAB L* function
and the mapping between raw hardware brightness value and relative
luminance is unknown, the implementation allows user to fine-tune the
exponent.
=> backlight: support nonlinear brightness

blocks.md, src/blocks/temperature.rs
Allow using the Fahrenheit temperature scale in the Temperature block's display and thresholds.
In order to adjust the default thresholds based on the scale used, I've used Options to provide delayed initialization in `Temperature`'s `new()`, rather than when serde deserializes the configuration. Alternatively I think we could manually deserialize the struct.
=> temperature: Add Fahrenheit support.

src/blocks/kdeconnect.rs
Same as the issue described in #904 but for the kdeconnect block
=> kdeconnect block: fix panic when no icon exists

src/blocks/battery.rs
=> battery block: clamp 'time remaining' values to something more realistic

src/blocks/keyboard_layout.rs
get_inputs() can return both a mouse/pointer and a keyboard with the
same identifier. find the keyboard.
fixes #917
=> make sure to try get the layouts from an actual keyboard

src/main.rs, src/util.rs
Fixes https://github.com/greshake/i3status-rust/issues/349
@GladOSkar would you like to give it a go and see if it's fixed? Testing with the below config showed the colours match the current behaviour so I assume it's working:
```toml
[theme]
name = "slick"
[theme.overrides]
separator = "SEPARATOR"
[icons]
name = "awesome"
[[block]]
block = "time"
[[block]]
block = "time"
[[block]]
block = "time"
[[block]]
block = "time"
```
=> Fix alternating tint logic when blocks are hidden

src/blocks/net.rs
"Malformed JSON" doesn't make sense as an error since if the JSON itself was
invalid then serde would catch it earlier. We will trust that `ip` is outputting
a valid response, and if that response contains no ip address info then we can
just return None instead of erroring out.
=> net block: do not error out when arrays are empty

src/util.rs
In response to #925 
I restructured and cleaned up a lot which turned out not to be necessary for the final solution but might be nice anyways. I don't think i introduced any regressions but that should be tested.
Alternating tint is now anchored to the right by counting the visible blocks beforehand and starting the alternating sequence accordingly on the left.
I barely have any rust experience, please lmk if something could be done better :)
=> Layout + tinting rework

src/blocks/battery.rs, src/blocks/networkmanager.rs, src/blocks/sound.rs, src/widgets/text.rs
related to #900 .
If the battery if fully charged, then the percentage does not have an additonal space.
Same if the volume if muted (and percentage not printed)
=> [blocks] fix equal spacing in battery & sound & networkmanager

src/blocks/music.rs
When collapsed there is no longer a superfluous space after the music icon.
There is (hopefully?) no longer any superfluous spaces between the play/prev/next buttons.
There might be some more work to do on this but will go with this for now.
=> music block: fix widget spacing

src/blocks/music.rs
So for some reason my `music` block wasn't hiding with `hide_when_empty = true` even though i had no players open.
This change fixed that, although i don't _really_ know why or what the different variables actually mean.
Hope this is okay?
=> Music block: Fix `hide_when_empty` not working

blocks.md, src/blocks/keyboard_layout.rs
Otherwise it would panic on startup if `sway_kb_identifier` was set to an empty string. Now it will just grab the first input found, and even though it may not be a useful one it's better than crashing the bar.
=> keyboard_layout: add default fallback for sway driver

src/themes.rs
Resolves #952
@GladOSkar﻿ I'm guessing removing it was unintentional? Or was it removed because after #924/#927 we found that it wasn't actually being used anywhere?
=> Re-add `alternating_tint_fg`

src/config.rs, src/themes.rs, src/util.rs
This should resolve #965, however I wonder if it could be made better by dropping the `native_separator` key and somehow using `separator` itself (by special casing "None")
=> Bugfix for issue 965

src/blocks/music.rs
=> music block: handle case when metadata is unavailable

README.md
`i3status-rust` is now availble as a [Home Manager](https://github.com/nix-community/home-manager) module for installation!
[Home Manager](https://github.com/nix-community/home-manager) provides for a declarative way to set up userland programs on all Linux distributions and MacOS (using [nix-darwin](https://github.com/LnL7/nix-darwin)) and is also a popular choice on NixOS.
Checkout [the list of available module options for i3status-rust here](https://nix-community.github.io/home-manager/options.html#opt-programs.i3status-rust.enable).
=> Document availability in home-manager

blocks.md, src/blocks/net.rs, src/blocks/speedtest.rs, src/util.rs
I was annoyed by the fact that the ping in the `speedtest` block always has 2-3 decimals, not adhering to the `speed_digits` option that the up/down values use.
So i changed the `format_speed` function to `format_number` and made it unit-agnostic so it can be used for any SI-scaled units.
What do you think @ammgws?
(Maybe technically there should be a separate `ping_digits` but i figured that'd be overkill)
=> Add universal formatter

src/blocks/net.rs
It so happens that my home SSID name has some Lithuanian characters. That inspired me to implement escaped unicode decoding for the SSID names which was discussed here https://github.com/greshake/i3status-rust/issues/293#issuecomment-442554796 some time ago.
I am a beginner in Rust so any feedback is greatly appreciated and will be quickly addressed. :)
=> Decode escaped unicode in SSID

src/blocks.rs, src/blocks/base_block.rs, src/blocks/battery.rs, src/blocks/cpu.rs, src/blocks/custom.rs, src/blocks/custom_dbus.rs, src/blocks/disk_space.rs, src/blocks/docker.rs, src/blocks/focused_window.rs, src/blocks/github.rs, src/blocks/ibus.rs, src/blocks/keyboard_layout.rs, src/blocks/load.rs, src/blocks/maildir.rs, src/blocks/music.rs, src/blocks/net.rs, src/blocks/networkmanager.rs, src/blocks/notmuch.rs, src/blocks/nvidia_gpu.rs, src/blocks/sound.rs, src/blocks/template.rs, src/blocks/time.rs, src/blocks/uptime.rs, src/main.rs, src/widgets/graph.rs, src/widgets/rotatingtext.rs, src/widgets/text.rs
This PR allow allow all blocks to support `on_click` properties by implementing following things:
1. Add `BaseBlock` for common properties for blocks (right now only 'on_click')
2. Allow child block override this `on_click` behavior by adding a trait method in `Block` trait. It is because some blocks maybe have a complicated flow for clicking.
3. Added id for `TextWidget` ,`GraphWidget` and RotatingTextWidget` for letting `I3BarEvent` name available.
It partially fixes #697, other common properties could be added in the same fashion later.
Document is lacking, but will be submitted later if needed.
=> Implement on_click for all blocks

Cargo.lock, Cargo.toml, blocks.md, src/blocks/docker.rs, src/blocks/github.rs, src/blocks/weather.rs, src/http.rs, src/main.rs
This commit makes the weather block use the curl bindings through the
`curl` crate rather than start a sub process to execute the curl binary.
This has a few advantages:
- Is faster and uses less resources as no shell is started
- We can use simpler code to parse the errors, status codes and output
- The user does not need to depend on the `curl` binary.  The `curl`
crate depends on `curl-sys` which can be configured to link to libcurl statically or dynamically.
Change the `docker` and `github` blocks to use these bindings as well.
Additionally, some improvements to the weather block were implemented:
Allow the user to configure the block with coordinates in addition to `city_id` or `place`.
Implement new format specifier `wind_kmh` with the value of wind speed in km/h. This is a feature …
=> Refactored weather block to use curl crate

blocks.md, src/blocks/taskwarrior.rs
Hi there!
First of all, thanks for the work on this great project. It's something that I use every single day, and is always visible on my monitor  and working very well :-)
Secondly, this is my first contribution to this project, so apologies in advance if I've missed something.
------
This PR addresses #905 and generalizes the Taskwarrior block by supporting an arbitrary number of filters.
Multiple filters can be specified as follows:
```toml
[[block.filters]]
name = "today"
filter = "+PENDING +OVERDUE or +DUETODAY"
[[block.filters]]
name = "work"
filter = "proj:work +PENDING +OVERDUE or +DUETODAY"
```
Deprecations:
* `filter_tags` are deprecated in favour of `filters`
* `TaskwarriorBlockMode` is removed in favour of `filter_index` since we can now cycle through all filters
* If …
=> Support multiple filters in Taskwarrior block

src/blocks/speedtest.rs
In #1018 I accidentally assumed that `ping` is stored in milliseconds whereas it is in seconds.
=> fix speedtest

blocks.md
By omitting the patch version, the link redirects to the latest release of the given (minor) version, which should match Cargo's behavior.
=> Update time-block docs to link to current chrono version

blocks.md, src/blocks/github.rs
Similar to #982. Add an option to hide the block if no notifications are available. Please comment on this PR so that I can check if it works.
=> github: add an option to hide when no notifications are available

src/blocks/backlight.rs, src/blocks/battery.rs, src/blocks/custom.rs, src/blocks/ibus.rs, src/blocks/keyboard_layout.rs, src/blocks/sound.rs, src/blocks/taskwarrior.rs, src/blocks/uptime.rs
Use `block_error()` if possible since it makes code mode readable. Also handle some DBus errors instead of doing `unwrap()`.
=> Refactoring: use `block_error()` and handble DBus errors in battery.rs

blocks.md, src/blocks/keyboard_layout.rs
If I'm right, sway's keyboard layout is either `layout (variant)` or `layout` if there is no variant. If so, then it is possible to implement [this TODO](https://github.com/greshake/i3status-rust/blob/aaec57f85e150eaa0b13c5a4238df16b41649e41/src/blocks/keyboard_layout.rs#L365).
=> keyboard_layout: split layout name and variant in sway driver

blocks.md, src/blocks/cpu.rs, src/blocks/keyboard_layout.rs
An attempt to solve an issue discussed in #688 by moving the percent symbol inside `{utilization}` and include "GHz" directly in `{frequency}`, because per-core code assumes that anyway. This allows me to revert changes introduced in #688 and thus make the block customizable again.
Closes #1029
=> cpu: fix "{frequency}" format in per-core mode

blocks.md, src/blocks/hueshift.rs
Resolves #1026. Also now the block shows an error if it couldn't find a program to use, because having a block that behaves like it's working whereas it doesn't doesn't feel right.
In addition make the internal structure more like in `keyboard_layout` block.
Note that `gammastep` does not allow to to change it's state smoothly (or I just couldn't find a way to do so), current implementation `killall gammastep`s before it sets a new temperature. This results in flickering.
If I get I right, `gammastep` has to be running in order to work, it cannot just exit like `redshift`. Maybe it's a limitation of wayland?
=> Hueshift: add support for gammastep

src/util.rs
When I fist read the code I thought that `format_number` should format numbers to [engineering notation](https://en.wikipedia.org/wiki/Engineering_notation), but in fact it produces outputs like "0.43MB" instead of "430KB", even if the minimal suffix is set to "K". For me, it doesn't make much sense. Please correct me if the current behavior is intentional.
=> Fix format_number function

src/config.rs, src/main.rs, src/themes.rs, src/util.rs
Manually `impl<'de> Deserialize<'de> for Theme` which gives more flexibility than having two `Config` structs and trying to deserialize one and then another. This solution is similar to what `icons` has.
Full compatibility is preserved.
Future thoughts: don't copy the entire config to every block. Instead, give each block something like `Rc<Icons>` and `Rc<Theme>` (maybe create struct "appearance"?), and clone the theme only if block has theme overrides. As far as I know, blocks need global config only for theme and icons, please correct me if I'm wrong.
=> remove redundant ConfigLegacy structure

src/themes.rs
Resolves #1054
This looks like a hacky workaround. But this also gives ability to have different requirements for themes in files than for themes in configs. I don't see use any cases yet, but maybe there are some.
=> fix loading theme form file

themes.md
Adds a mention to the possibility of overriding the theme locally within a block using the `color_overrides` option. I could not find any mention of this option anywhere; I had to go looking into the code wondering whether this was even technically possible, only to find that it was already implemented; just not documented.
It could be argued that this modification belongs to the blocks documentation, or in both places; feel free to change it if you deem it better.
Also, I guess the man pages should be regenerated but I do not have pandoc installed... I would appreciate it if anybody can run the generation script and add the commit to the pull request before potential merging...
=> Add documentation for color_overrides

blocks.md, src/blocks/net.rs
Adds an ability to have two different formats and switch between them by just clicking on the block. For example, there is no need to constantly monitor your ssid, but is is nice to be able to click and see what is it.
=> net: add `clickable` option and `format_alt` formating option

blocks.md, src/blocks/temperature.rs
=> Add fallback for older systems that don't have `sensors -j`

src/blocks/sound.rs
Resolves https://github.com/greshake/i3status-rust/issues/1001#issuecomment-780498034
Test run to see if this can be applied to all blocks using format strings
=> sound block: fix spacing for empty format strings

src/blocks/net.rs
The `Net` struct has some fields that are marked as `Option` but they are always `Some`. Remove the option. Also print "N/A" when trying to get ssid or signal strength when wired connection is used instead of throwing an error.
TODO:
=> net: refactoring

blocks.md, src/blocks/net.rs
Solve TODO from #1072. Those options don't do anything anyway. The "hide" functionality works as before.
Also add documentation for `max_ssid_width` option.
In addition this solves issue with double space.
=> net: remove deprecated options and redundant widget

src/blocks/net.rs, src/blocks/sound.rs, src/blocks/temperature.rs, src/main.rs, src/util.rs, src/widgets/graph.rs, src/widgets/rotatingtext.rs, src/widgets/text.rs
Currently if built in debug mode, even if profiling is disabled, `i3status-rs -h` gives this:
```
--profile <profile>
--profile-runs <profile-runs>
```
which is not correct.
Also fix some clippy warnings and remove
```rust
#[macro_use]
extern crate serde_json;
```
because it isn't necessary since edition 2018
=> fix clippy warnings; show profiling options only if profiling is enabled

src/blocks/weather.rs, src/util.rs
Current implementation of formatting is somewhat messy. This is my attempt to rewrite it.
This implementation does not use recursive functions and the data structure is just a vector instead of custom linked list.
Probably needs some testing.
=> Simplify `FormatTemplate`

src/widgets/i3block_data.rs, src/widgets/rotatingtext.rs
A small bugfix for #1085:
- fix rendering of "align" option
- allow "min_width" option to be in pixels
Found those while trying to fix some spacing-related issues by moving each icon into it's own widget. Is this a reasonable idea and have someone tried this before? In some fonts each icon occupy two characters and overlaps with the next character. In some fonts this doesn't happen. If each icon had it's own widget, user would be able to set the size of the icon and it's align.
=> I3BlockData: allow `min_width` in pixels; fix `align` rendering

src/widgets/rotatingtext.rs
With this fix it is possible to override music icon to something like that:
```toml
music = " <span size='medium' font_family='NotoSans Nerd Font'>\uf886</span> "
```
Currently, if this override is applied, music widget will get very wide.
=> rotatingtext widget: fix `min_width` calculation

src/blocks/net.rs
The net block now correctly displays the SSID instead of the BSSID when `wpa_cli` is used and fixes #1100
=> Fixed wpa_cli BSSID being displayed instead of SSID, see #1100

src/config.rs, src/de.rs, src/icons.rs, src/themes.rs, src/util.rs, themes.md
- With this PR it is now possible to load icons from a separate file, just like themes
- User can omit `.toml` extension when loading a theme or an icon set from a file
- All this takes 27 lines less compared to previous implementation!
=> Refactor icons deserialization and add ability to load icons from file

themes.md
By the way, `theme_overrides` doesn't work in [`v0.14.7`](03d4fdfcc043e0c61b268bc295fe554f42d602b3). I guess the reason is 3030efebe7a1f3e73eedb697919829910026b737 (#1042) is not in there.
=> Typo in themes.md: `color_overrides` -> `theme_overrides`

blocks.md, src/blocks/sound.rs
This adds the usage of Pulse device descriptions (more human friendly names) (without breaking mapping).
Also the `output_name` now can have a `max_width`.
=> Add description and max_width to sound block

src/blocks/networkmanager.rs
This fixes #1117 and #991. (For explanation see #1117)
Also as a nice side effect the wifi signal strength now updates.
**But** I was debugging a bit and noticed that the block now updates 14 times when a connection is disabled and 19 times when a new wifi connection is added that seams a _bit_ excessive (most of the time nothing changes between updates, because we listen for properties we don't display). Removing the rule for `/org/freedesktop/NetworkManager` helps, but it's still not great (7-10 updates) and we could miss events (again).
I have looked a bit into the dbus crate, but didn't manage to deconstruct or filter an event (jet)...
=> Add additional match rule for active connections

doc/blocks.md, src/blocks/nvidia_gpu.rs
I am interesting in monitoring my GPU's power usage at a glance
so I added this quick feature.
I had initially added this to the `v0.14.7` branch/tag but decided on
master as it seemed like that was where other efforts were being
focused.
If you're not interested in this change, or would like to see more
(I know I didn't add any tests, let me know if that is a dealbreaker)
let me know. Thanks! (I'm not sure if the manual pages are
auto-generated from the comments/code; that is another area
where I could have very easily missed something necessary)
Screenshot of this working on my branch with the no theme nor
icons specified:
This fits in with the existing `nvidia-smi` invocation.
I fit this at end of the Nvidia block, as it seemed visually appealing
there (this did mean some `count++` and …
=> Include "Power Draw" option for Nvidia GPU block

src/blocks/music.rs
I think it makes more sense like this, the block should be as little intrusive as it can be while no music plays.
"Not playing" states are "Paused", "Stopped" and "Unknown".
=> music: set state to idle when the music is not playing

src/widgets/rotatingtext.rs
Some titles contain `&` and other symbols that should be escaped.
=> music block: escape pango

src/widgets/rotatingtext.rs
This field was only filled when not necessary (ie. when `text_width >= max_width`) with `dynamic_width` set to `true` but would potentially add a padding when not using a fixed sized font.
I personally encountered this issue while using the music block.
=> widgets/rotatingtext: never provide `min_width` for dynamic width

doc/blocks.md, src/blocks/weather.rs
localized weather in the description field
default
```toml
[[block]]
block = "weather"
format = "{weather} {weather_verbose}"
service = { name = "openweathermap", api_key = "", city_id = "1799962", units = "metric"  }
```
```json
[{"full_text":" WEATHER \"Clouds\" \"overcast clouds\" ","name":"0","instance":"0","markup":"pango"}]
```
zh
```toml
[[block]]
block = "weather"
format = "{weather} {weather_verbose}"
service = { name = "openweathermap", api_key = "", city_id = "1799962", units = "metric" , lang = "zh"}
```
```json
[{"full_text":" WEATHER \"Clouds\" \"阴，多云\" ","name":"0","instance":"0","markup":"pango"}]
```
=> weather: support config language

src/blocks/focused_window.rs
Block would fail to render text containing `&` or `<` with pango emitting errors e.g:
pango_layout_set_markup_with_accel: Error on line 1:
Entity did not end with a semicolon; etc.
I've used the [html-escape crate](https://crates.io/crates/html-escape) which may be overkill for this but was easiest. I can write a smaller implementation if you don't want to take the dependency.
=> Escape html entities in focused_window block

examples/README.md
Sharing my custom block for the local ads blocking server [https://pi-hole.net/](https://pi-hole.net/). I'd be happy to get a feedback :slightly_smiling_face: 
It partially replaces previous "native" implementation: #1007
In response to: https://github.com/greshake/i3status-rust/pull/1007#issuecomment-838414515
=> Adds example for custom pi-hole status block

src/errors.rs
JSON of `ConfigurationError` which is passed to i3bar is separated by newline.
Because of that, a JSON parsing error is displayed by i3 instead of the proper i3status-rs error message.
before:
```
[{"full_text":" Configuration error: failed to parse TOML from file contents.
Cause: expected an equals, found a newline at line 1 column 13 ","color":"#dc322f","background":"#000000","name":"0","instance":"0","separator":false,"separator_block_width":0,"markup":"pango"}],
```
after:
```
[{"full_text":" Configuration error: failed to parse TOML from file contents. Cause: expected an equals, found a newline at line 1 column 13 ","color":"#dc322f","background":"#000000","name":"0","instance":"0","separator":false,"separator_block_width":0,"markup":"pango"}],
```
Discussed in #1222 
Note: Escaping …
=> Fix json output of configuration error

doc/blocks.md, src/blocks/apt.rs, src/blocks/battery.rs, src/blocks/bluetooth.rs, src/blocks/cpu.rs, src/blocks/disk_space.rs, src/blocks/docker.rs, src/blocks/github.rs, src/blocks/ibus.rs, src/blocks/kdeconnect.rs, src/blocks/keyboard_layout.rs, src/blocks/load.rs, src/blocks/memory.rs, src/blocks/music.rs, src/blocks/net.rs, src/blocks/networkmanager.rs, src/blocks/notify.rs, src/blocks/pacman.rs, src/blocks/sound.rs, src/blocks/speedtest.rs, src/blocks/taskwarrior.rs, src/blocks/temperature.rs, src/blocks/time.rs, src/blocks/weather.rs, src/blocks/xrandr.rs, src/errors.rs, src/formatting.rs, src/main.rs, src/widgets.rs, src/widgets/text.rs
This is mostly a port from `MaxVerevkin/swaystatus@b26224d` and based on the discussions from #1205.
It works quite well for me.
Things that could be improved are:
- `RotatingTextWidget`s can't be shortened from the format string, the interface doesn't really facilitate that. This only impacts the `music` block afaik. Something for a future PR imo.
Feedback + testing appreciated :)
=> Add short_text support

examples/README.md
Here I'm adding an example block for displaying information from `liquidctl` tool. 
And here how it looks like:
=> Custom block example: liquid cooling system status

src/blocks/pacman.rs
Fixes #1238
`PacmanConfig::watched()` was using a version of the `FormatTemplate` that didn't include the default format.
Please test as i don't have `pacman`, although according to my debugging it should work now
=> pacman: fix default template not being used for `PacmanConfig::watched()`

src/blocks/pacman.rs
Need to revert back to calling `fakeroot` via `sh` since there seems to be some quoting issues otherwise.
=> pacman: fix invocation of fakeroot/pacman command

src/formatting/placeholder.rs
Now format strings like `"{speed_down*_}"` work correctly - it hides the
unit but does not override the default setting.
=> format strings: fix parsing of "unit" part

src/formatting.rs, src/formatting/placeholder.rs, src/formatting/prefix.rs, src/formatting/unit.rs, src/formatting/value.rs
Closes #1228
Closes #1242
Possibly closes #1243
- Rewrite formatting strings' parsing
- Remove a test that checks the internal representation of `FormatTemplate` (why did I write it in the first place?)
- Allow to hide the prefix (`"{key;_K}"` sets the min prefix to "K" and hides it)
- Allow a space between the value and prefix/unit (`"{key; K*b}"` results in `"val Kb"`, `"{key; _K*b}"` results in `"val b"`)
- TODO: update the docs
=> formatting: refactor, implement prefix hiding and spacing

src/blocks/battery.rs
cc https://github.com/greshake/i3status-rust/pull/1258
cc @orvij
=> battery: fix array out of bounds access when directories with only 2 letters are encountered in /sys/class/power_supply

doc/blocks.md, src/blocks/battery.rs
Resolves #875
Partially addresses #1254
Usecases:
- TLP (or other) setups that intentionally only charge to a certain percentage
- Aftermarket batteries that don't achieve the full charge necessary to show up as full in the sysfs
=> battery: Add `full_threshold` option for setups that don't reach 100%

src/config.rs, src/errors.rs, src/protocol/i3bar_block.rs, src/protocol/mod.rs, src/themes.rs, src/util.rs, src/widgets.rs
by creating `Color` enum and using `serde` to parse it from theme/config overrides.
Based on @MaxVerevkin's implementation in [MaxVerevkin/swaystatus@1c2516a](https://github.com/MaxVerevkin/swaystatus/commit/1c2516abeee95a7c6f42cac59b1b186c9698fe68) with a few changes.
Resolves #1276
=> Add possibility to unset colors using overrides

src/blocks/weather.rs
A degree symbol is added by the Unit formatter already, so there should
not be an additional one added in the default format string.
=> Weather: Remove duplicate degree symbol from default format

src/http.rs
Fixes failures in Weather block when place names have a space in them. Simplified version of #1287 based on feedback received there.
=> http: Replace spaces in URL with "%20"

README.md
This has been tested by using a Docker image to replicate a fresh Ubuntu install. I chose to do it on Ubuntu since it's the distro mentioned in #1268, and is also a very common distro.
=> Update compilation requirements according to #1268

examples/config.toml, examples/config_icon_override.toml, examples/config_theme_override.toml
The example configurations come with a memory block which displays total memory used, including buffers, cache, and ZFS ARC. I would imagine the majority of people do not want this, and would rather see the amount of memory available for applications.
It appears the example used to work this way, but was changed in https://github.com/greshake/i3status-rust/commit/04105c7535e1fc6100ce76bb4bb2bfc4f69d8656 (perhaps accidentally?) to include buffers/cache.
`Mup == mem_used_percents`
`MUp == mem_total_used_percents`
https://github.com/greshake/i3status-rust/blob/v0.20.2/NEWS.md
=> Display "available" memory instead of "free" memory in examples

README.md
As discussed [here](https://github.com/greshake/i3status-rust/pull/1300#issuecomment-909378597).
The current version is using the packager-agnostic of the dependencies on the build dependencies, and apt names on runtime dependencies.
The reasoning for using apt names are to simply make it easy for beginners, who are a lot likely to be running debianlike distros (apt). People not using debians are more likely to be more experienced, and therefore more likely to have those dependencies already installed, since a lot of things depends on them.
The reasoning for not doing so is that this program is made for a tiling style window manager, which may already imply the user isn't quite novice, and can find their way on their own packagers.
This doesn't completely invalidate the reason for making …
=> Changed packager-agnostic name on requirements to package name on apt

doc/blocks.md, src/formatting/value.rs
Also removes trailing whitespace from `doc/blocks.md`.
=> Fix typos, correct icon names for sound block

doc/blocks.md, src/blocks/docker.rs
Allows configuration of the docker socket path so that non-default installations such as rootless-mode can use to block.
fixes #1309 
```
[[block]]
block = "docker"
format = "T:{total} R:{running} S:{stopped} P:{paused} I:{images}"
interval = 60
[[block]]
block = "docker"
format = "T:{total} R:{running} S:{stopped} P:{paused} I:{images}"
interval = 60
socket_path = "/run/user/1001/docker.sock"
```
=> allow non-default docker setups

doc/blocks.md, src/blocks/sound.rs
This allows to dynamically change sound block icon when headphones are plugged in/out. I've made it off-by-default since it may not work for people with weird audio setups.
=> Add optional headphones indicator to sound block

src/main.rs, src/scheduler.rs
Previously closing the player would allow no further updates to be scheduled, since song change and right-click events would only be processed directly and not add to the scheduled queue (they could not schedule further events - necessary for the marquee).
This is fixed by making these events add to the scheduler queue _if_ the block does not currently have any update scheduled. So simply playing a new song or right-clicking the block will make the marquee start scheduling events again :)
See issue #1124 for more details.
This has been tested with the music block and seems to work well, it may be worth quickly checking other blocks to make sure that none of them rely upon the `update_requests` channel never scheduling further events.
Note that writing to the scheduler directly like this …
=> Fix music marquee updates after closing player

src/blocks/hueshift.rs
This commit adds support for wlsunset and should close  #1316.
As I was reading how redshift/gammastep and sct do things so that I could make the behavior for wlsunset as simiar as possible, there were a couple of things to note.
1. While wlsunset has a gamma option, there does not seem to be an option to reset the gamma ramps like redshift/gammastep. I skimmed through wlsunset's code, and it seems like it might handle that automatically. I am going to leave the gamma CLI argument alone for now.
2. redshift/gammastep have a color reset option, sct and wlsunset do not. On the [github README for sct](https://github.com/faf0/sct), it states "_If `xsct` is called without parameters, **the current display temperature is estimated**._" (emphasis mine) I do not know what this means at a glance. …
=> hueshift block: Add support for wlsunset

src/blocks/sound.rs
Add detection for headset, earpiece and handsfree devices.
Taken from https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/blob/0ce3008605e5f644fac4bb5edbb1443110201ec1/src/pulse/def.h#L1073-1100
=> sound: detect more portable speaker types

doc/blocks.md, src/blocks/backlight.rs
The `backlight` block has a few configuration differences compared to `sound`, the last of which may be considered a bug.
- there is no `format` option (`volume` has one)
- `on_click` does nothing by default  (`volume` toggles on click)
- `on_click` override _erases the preset scroll action_ of changing brightness by small increments (scrolling on `volume` is still available when `on_click` is set)
This PR fixes these three differences by adding behavior to the `backlight` block:
- `format` is by default set to the only placeholder available, `"{brightness}"`
- by default, both left and right clicks "toggle" brightness (same as `volume`)
- if `on_click` is set, left click becomes `on_click` and right click remains the default toggle (same (I think) as `volume`)
"toggle" brightness: if …
=> `backlight` block: adapt configuration options to precedent set by `sound` block

files/icons/material-nf.toml
Can't use `material-nf` without getting an error if I disconnect and reconnect a device that has a battery block like my mouse for example. 
(Seperate issue) It flags the mouse as unavailable since it increments on re-connection, i.e. `mouse_hidpp_battery_1` to `mouse_hidpp_battery_2`, not sure how to workaround that problem, since I frequently disconnect my mouse.
=> Add missing bat_not_available icon

src/blocks/docker.rs
Trivial change - if we can't connect to the docker daemon, change the color.
A very typical reason for not being able to connect (on top of course of the daemon being down, but I don't know if that's typical on a properly configured system) is that the user doesn't have permissions to access the socket file. 
Anyway, I prefer to make it obvious,  but feel free to close the PR.
=> docker block: Mark errors as critical

doc/blocks.md, src/blocks/focused_window.rs, src/blocks/net.rs, src/util.rs, src/widgets/rotatingtext.rs
This PR adds format support to the block focused_window.
The reason I need this is that I really want all my blocks to have a fixed width (not just maximum, also minimum) because I find it annoying when a block changing width moves the location of all the rest.
So I have this now in my config:
```
[[block]]
block = "focused_window"
max_width = 100
show_marks = "visible"
format = "{composed:50^50}"
```
=> Focused window format

src/blocks/sound.rs
This reverts commit 5611e2dd7302b62c3a4e4883c7291f1d2f4d765f.
As explained in https://github.com/greshake/i3status-rust/pull/1348#issuecomment-984894163 this change is not correct. The PR mentions port types, but it's port names that are being queried. 
Alternatively I can make a change to query port types instead of names, but as mentioned [here](https://docs.rs/libpulse-binding/2.25.0/libpulse_binding/context/introspect/struct.SinkPortInfo.html#structfield.type) that would require building `libpulse-bindings` with support for pulseaudio v14, breaking support for older pulseaudio versions. Not sure if that's a concern or not.
=> Revert "sound: detect more portable speaker types"

src/blocks/networkmanager.rs
This fixes error messages from sway when the SSID contains unescaped characters like `&`.
=> :bug: Escape SSID in NetworkManager

doc/blocks.md, src/blocks.rs, src/blocks/external_ip.rs, src/formatting.rs, src/formatting/value.rs, src/util.rs
Display our external IP address and information about it (country, region, location, ISP, etc). 
- To test
```
[[block]]
block = "external_ip"
format = "{address} {country} {country_code} {region} {region_name} {city} {zip} {latitude} {longitude} {timezone} {isp} {org} {autonomous_system} {country_flag}"
```
- Possibly some non-rustic code there, feel free to school me.
- serde_derive and service don't get really well (both export Serialize). Used an alias for one of them. Proper solution welcome.
- Using a free API to get all the info. Only limitation this API has that we might sort of care about is that it's http, not https (on the free tier).
- Includes country flag representation but it requires a font that includes them. See blocks doc for details.
-Tested with IPv4 only.
=> Create block to display external IP address information

doc/blocks.md
Simply adds a relevant example to docs/blocks.md
=> Add keyboard layout switching example to blocks docs.

build.rs
Users may have set variables for git's config that cause the output
data to be in an unexpected format.
For example I have the following set:
```
[commit]
gpgsign = true
```
Causing my version to look like:
```
i3status-rs 0.20.8 (commit b5dec12 gpg: Signature made Wed 29 Dec 2021 11:43:07 PM CST)
```
Instead of:
```
i3status-rs 0.20.8 (commit b0b8b7c 2021-12-31)
```
We can tell get to ignore the user's .gitconfig by setting the
environment variable `GIT_CONFIG_GLOBAL=/dev/null`
=> Fix version info collect at build time

src/blocks/battery.rs, src/blocks/nvidia_gpu.rs, src/blocks/sound.rs, src/blocks/temperature.rs
Currently the full format for the battery block uses the hidden spacing.
However the hidden spacing should only be used when there's no tokens
in the full format.
=> Fix battery block's spacing

src/blocks/rofication.rs
Simple modification to support both versions of rofication.
- Send b"num:\n" instead of b"num\n". This works because both versions split by : first (to separate the command from its arguments). Since "num" has no arguments, the newline is discarded by the original rofication (which doesn't like it) and present for the fork (which needs it).
- If the output is new-line separated (case of the original one) we convert that to commas so we can then split by it.
So trivial diff here.
Tested by replacing the fork rofication with the original one. Of course other things don't work since well, regolith needs its fork :-) But our block works with both versions now.
=> Make rofication block support both the original version and regolith's fork

doc/blocks.md, src/apcaccess.rs, src/blocks/battery.rs, src/main.rs
Added new apcupsd battery driver called apcaccess (like the command
line tool wich is used to query apcupsd for status and events).
Added information about new driver to blocks.md
=> Add new apcupsd battery driver

doc/blocks.md, src/blocks/keyboard_layout.rs
Closes #1384
If you set the xkbmap layout to a multilingual string with variants, such as:
```
setxkbmap -layout us,es,ru
setxkbmap -variant dvorak,,phonetic
```
the `keyboard_layout` block will not show the current layout nor the current variant. It will only show the entire multilingual layout string. This is because `i3status-rust` uses the command [`setxkbmap -query`](https://github.com/greshake/i3status-rust/blob/b6e1b0b755de9f4520f1ecf17086d62fc5f190fe/src/blocks/keyboard_layout.rs#L63) to get the current layout.
```
$ setxkbmap -query                 ☸ 0007-04
rules:      evdev
model:      pc105
layout:     us,es,ru
variant:    dvorak,,phonetic
options:    grp:ctrls_toggle
```
This pull request uses [`xkb-switch`](https://github.com/grwlf/xkb-switch) to read the current layout and …
=> Add support for the xkb-switch keyboard layout reader.

doc/blocks.md, src/blocks/battery.rs
Added additonal match filters in the monitor function to let us know
when a upower devices is added or removed.
Implimented the is_availible function for UpowerDevice.
Deduplicated logic in Battery's update function regarding the return
values.
Updated blocks.md to remove note about allow_missing not working for
drivers other than the sysfs driver.
=> Enable allow_missing for the UPower driver

src/apcaccess.rs, src/blocks/battery.rs
@ammgws pointed out that UPower devices were throwing an error if the
device was not present when the bar started. If the battery has
`allow_missing=true` this is not a case that we want to throw an
error. There was a similar issue present in the new apcaccess
battery driver that is fixed as well. Both drivers are able to
pull information from a device is that not present when the status
bar is launched, when `allow_missing=true`.
=> Fix for batteries allow_missing

src/blocks/hueshift.rs
The usage of killall is unreliable when using wrapped executables such
as gammastep installed from the Nix package manager. When killall
doesn't kill the process, many hueshifting processes build up which
result in monitor flicker, total blackout, etc.
Addresses #1397
=> hueshift: Replace killall with pkill

Cargo.toml
crates.io requires a license expression from here:
http://opensource.org/licenses for options, and http://spdx.org/licenses/ for their identifiers
We do need to have a published crate on crates.io as Debian packaging scripts require it.
I published 0.21.1 -from master, no changes- with this license (the alternative is GPL3 or later instead of exactly 3.0), feel free to discard this PR and update with the other one if that's preferred.
=> Use a standarized license expression ( "GPL-3.0-only" instead of "GPLv3" )

src/blocks/battery.rs
Fixes #1405 
State and Type need to be read in as u32 not i32.
This was missed when testing with `allow_missing = true`
=> Issue-1405: UPower property type mismatch

doc/blocks.md
#externalip is the correct anchor as there is no space in title `ExternalIP`.
=> Fix a typo in blocks.md

examples/config.toml
Test for existance, not for regular file.
=> Adjust example; BAT0 is typically a symlink

doc/blocks.md, man/i3status-rs.1, src/blocks/hueshift.rs
Add support for wl-gammarelay.
While reviewing hueshift.rs It was noted that `Hueshift::update`
does not need to be called on the `update_interval`.
If drivers have a way of polling for the current temperature then it
makes sense to have an update interval otherwise it has no effect.
None of the drivers besides WlGammarelay has a mechanism to get the
current temperature if they are changed outside of the statusbar.
Although WlGammarelay can get the current temperature it doesn't need
to run update on an update interval as it is listening to dbus events.
Something like this:
```
Ok(match self.hue_shifter {
HueShifter::X | HueShifter::Y => Some(self.update_interval.into()),
_ => None,
})
```
Updated man pages (it looks like it's been some time since this has been
done). Perhaps it would be …
=> Add wl-gammarelay driver for hueshift

src/blocks/sound.rs
DEVICE_FORM_FACTOR, if present, will be used to determine whether the
headphones icon is used. If it is not present, the existing active_port
method is used to determine if the headphones icon is used.
=> sound: check DEVICE_FORM_FACTOR property

doc/blocks.md, src/blocks/music.rs
Addresses #1396 
The `players` field holds an array of players, which, along with the `player`, will be considered as the preferred players.
I couldn't build due to some linking errors, but `cargo check`ed successfully.
=> Music: Add `players` field to the config

doc/blocks.md, src/blocks/disk_space.rs, src/blocks/maildir.rs, src/blocks/notmuch.rs, src/blocks/rofication.rs, src/blocks/watson.rs
As discussed in #1246, this runs `shellexpand::full` on paths the user might enter, thus expanding shell syntax like `~/file` and `${HOME}/file` to `/home/user/file`.
This is a created as a draft because I couldn't properly teste some of the changes, as I don't use these mail clients like a lot of users do, I take quite a beating from these cli clients, so I can't properly test maildir, notmuch and watson, all I could do is to try the config appropriately, and the error it spat out was not about _i3status-rust_'s config, or none at all, but I couldn't validate that I properly set up the program and whatnot. Watson requires extra attention because it uses `Pathbuf` on the config instead of `String`, like the others, since it needs it to spawn a watcher thread over it. I need some help …
=> Shellexpand on blocks

src/blocks/battery.rs
Some devices report a charge level rather than an accurate percentage.
This let's you specify the {charge_level} in the format string for
those devices.
=> Fallback to `charge_level` if `capacity` cannot be calculated

README.md
The correct argument is `never-pause` https://github.com/greshake/i3status-rust/blob/0fa0d0a4ca0992f947ffe567c8b1425349b1aa3b/src/main.rs#L71-L74 not `never-stop`
=> Fix argument in README.md

doc/blocks.md, src/blocks/battery.rs
As discussed in #1455, setting this option to `false` doesn't have any real use-cases. In addition, removing this option simplifies the code slightly. This is a breaking change.
=> battery: remove allow_missing

doc/blocks.md, src/blocks/net.rs, src/formatting.rs, src/formatting/placeholder.rs, src/formatting/prefix.rs, src/formatting/value.rs, src/util.rs
The documentation gives the following example in for the `net` block:
> Displays ssid, signal strength, ip, down speed and up speed as bits per second. Minimal prefix is set to `K` in order to prevent the block to change its size.
> 
> ```toml
> [[block]]
> block = "net"
> device = "wlp2s0"
> format = "{ssid} {signal_strength} {ip} {speed_down;K*b} {graph_down;K*b}"
> interval = 5
> ```
After seeing the `{graph_down;K*b}` part, I was quite confused, because I've assumed that the format specifier would be interpreted similarly to text based blocks (since the SI prefix part was being used).
This PR implements interpretation of the format specifier for the `net` block. This is useful if there is a desire to change the width of the graph (the previously hard-coded 10 characters are kept as a …
=> Net graph formatting

README.md
Also the ebuild was just updated to `v0.21.10`, see https://github.com/gentoo/guru/commit/b3e5021736614e390e259285ce509534b44370a2.
=> Added Gentoo instructions

src/blocks.rs, src/blocks/battery.rs, src/blocks/disk_space.rs, src/blocks/docker.rs, src/blocks/external_ip.rs, src/blocks/github.rs, src/blocks/keyboard_layout.rs, src/blocks/load.rs, src/blocks/maildir.rs, src/blocks/speedtest.rs, src/blocks/time.rs, src/blocks/uptime.rs, src/blocks/weather.rs, src/click.rs, src/main.rs
1. Send an update request when `update=true`. Previously, the event
would be passed through, but not every block updates itself on click
by default.
2. This heavily used pattern doesn't do what it seems to do:
```rust
tokio::select! {
_ = timer.tick() => (),
UpdateRequest = api.event() => (),
}
```
If `api.event()` returns a click event, it will just get discarded and
`api.event()` will not be called again until `timer.tick()` completes. In
other words, if you first click on a block and then ask it to update,
it... will not update. Use this instead:
```rust
tokio::select! {
_ = timer.tick() => (),
_ = api.wait_for_update_request() => (),
}
```
Fixes #1015
=> click handler: actually update the block when update=true

src/blocks/custom.rs, src/click.rs, src/main.rs
Do not cycle automatically.
Also I realized that something like
```toml
[[block]]
block = "custom"
shell = "sh"
cycle = ["echo '🐑'", "cat /etc/hostname"]
[[block.click]]
button = "left"
cmd = "<command>"
```
currently will not work because click handler will not pass the event to the block. This can be made configurable, like `pass = true` or something. With `true` as the default.
=> custom: fix cycle

src/blocks/music.rs, src/blocks/music/zbus_mpris.rs
Some song doesn't have title or artist tag. This PR implements reading `xesam:url` from MPRIS2 and expose it as `$url` placeholder. `$url` is also used by `$combo` now as a fallback when there's no title or artist info, so that there will be at least some info shown about the song.
=> music: add url field and use it as a fallback for $combo placeholder

src/blocks/keyboard_layout.rs
In the process of migration to async I saw that implementation for the kbdd keyboard driver is missing, so I decided to bring it back using zbus. This implementation is slightly different (and simpler) than the previous one, because before the layouts were parsed from setxkbmap -query command, mainly to save space and avoid the long names which kbdd provides. Now, with the option to map the output of a block to whatever the user wants, I've decided to use the strings from kbdd and to relay on the custom mappings for shorter names as the sway driver.
Also the widget was not added in the bar, so I've fixed that too in this PR.
=> Restore support for kbdd keyboard driver

NEWS.md, src/blocks/battery.rs
Add `empty_threshold` and `empty_format` to `battery`.
Also change `full_threshold` to `95` as batteries often do not go all the way up to 100%.
Should also fix #1431.
=> Add better support for empty batteries

NEWS.md, doc/themes.md, examples/config.toml, gen-screenshots/screenshot_config.toml, src/icons.rs, src/protocol.rs, src/protocol/i3bar_block.rs, src/themes.rs, src/themes/color.rs
Fixes #1578
Also merges `name` & `file` options into `theme`/`icons`. For example:
```toml
[theme]
theme = "solarized-dark"
[icons]
icons = "awesome"
```
=> config: remove top-level icons and theme

README.md, src/blocks.rs, src/blocks/custom.rs, src/config.rs, src/errors.rs, src/formatting.rs, src/main.rs, src/widget.rs
Implement a way for blocks to report (clickable) errors while still
being functional via `api.set_error()`.
`api.recoverable()` now uses `api.set_error()`.
Errors reported with `api.set_error()` provide the name of the block in
it's message, without the need for an explicit argument, just like
unrecoverable errors.
This makes it trivial to implement [this TODO](https://github.com/greshake/i3status-rust/blob/3eba9745309cd6261d4f7d51c1ee15e300ef674d/src/blocks/custom.rs#L128).
=> Rework blocks errors

src/blocks/focused_window.rs, src/blocks/music.rs
=> formatting: fix example configs which use `.str(<width>)`

src/blocks/net.rs
Add the `ip` and `ipv6` placeholders to the documentation of the `net` block.
=> docs: Add `ip` and `ipv6` to the `net` block docs

src/blocks/prelude.rs, src/blocks/weather.rs, src/errors.rs, src/formatting.rs, src/formatting/config.rs, src/formatting/formatter.rs, src/formatting/prefix.rs, src/formatting/template.rs, src/formatting/value.rs, src/widget.rs
fixes #1493
(This commit contains some unrelated renames and refactors)
`1i` is a special prefix which means "one but binary". `1i` is to `1` as `Ki` is to `K`.  This hack allows users to enable binary prefixes without setting `min_prefix`. If someone has a better idea, please share.
```toml
[[block]]
block = "disk_space"
format = "$available.eng(3,auto,1i)"
```
```toml
[[block]]
block = "net"
format = "$speed_down.eng(3,auto,Ki)$speed_up.eng(3,auto,Ki)"
```
=> formatting: add binary SI prefixes

src/blocks.rs, src/blocks/net.rs, src/blocks/speedtest.rs, src/config.rs, src/formatting.rs, src/formatting/formatter.rs, src/formatting/template.rs, src/formatting/value.rs, src/widget.rs
Resolves #1527
Will work nicely with #1618
Not documented yet. See `net` and `speedtest` for examples.
=> formatting: embed icons using ^icon syntax

src/blocks/disk_space.rs
Adds the `format_alt` option for `disk_space` block.
As per discussion in #1635
=> Add format_alt option for disk_space block

NEWS.md, src/blocks/temperature.rs
=> Add format_alt to temperature and remove collapsed

NEWS.md, src/blocks/memory.rs
=> memory: rename format_mem and format_swap to fromat and format_alt

doc/themes.md, src/protocol.rs, src/themes.rs
Thought i'd add this because it's such a simple change.
Should fulfill the given usecase. Maybe a bit simple/inflexible?
Always uses last widget's background color as foreground color and has no background color (bar color)
```
[theme]
theme = "gruvbox-light"
[theme.overrides]
separator = "<span font='15'></span>"
end_separator = "<span font='15'></span>"
```
Does this need documenting anywhere else? Not sure, didn't find other theming docs
=> Add option to add custom ending separator (resolve #1650)

doc/themes.md, src/blocks.rs, src/config.rs, src/main.rs, src/protocol.rs, src/themes.rs, src/themes/separator.rs, src/util.rs
Example usage (swap idle and warning colors):
```toml
[block.theme_overrides]
idle_fg = { link = "warning_fg" }
idle_bg = { link = "warning_bg" }
warning_fg = { link = "idle_fg" }
warning_bg = { link = "idle_bg" }
```
Fixes #1527
TODO: adjust docs.
=> Allow "theme overrides" colors to link to other colors

src/blocks/maildir.rs
```
cargo build --release --features 'pulseaudio maildir'
Compiling i3status-rs v0.30.0 (/home/bmalyn/Documents/Code/rust/i3status-rust)
error[E0596]: cannot borrow `config.inboxes` as mutable, as `config` is not declared as mutable
--> src/blocks/maildir.rs:60:18
|
57 | pub async fn run(config: Config, mut api: CommonApi) -> Result<()> {
|                  ------ help: consider changing this to be mutable: `mut config`
...
60 |     for inbox in &mut config.inboxes {
|                  ^^^^^^^^^^^^^^^^^^^ cannot borrow as mutable
For more information about this error, try `rustc --explain E0596`.
error: could not compile `i3status-rs` due to previous error
```
=> Fix change in maildir caused by #1652

doc/dev.md
`libsensors-dev` package is required to build the project.
Description:
Can't build i3status-rust on fresh ubuntu22 system because of lack of sensors library.
=> Install: Update dev.md

Cargo.lock, Cargo.toml, src/blocks/battery.rs, src/blocks/battery/upower.rs, src/blocks/bluetooth.rs, src/blocks/external_ip.rs, src/blocks/music.rs, src/blocks/music/zbus_mpris.rs
Fixes #1682 
In some cases `org.bluez` can disappear without any events (for example when it was `kill`ed).
When `org.bluez` disappears, `NameOwnerChanged("org.bluez", ..., "")` is emitted.
This commit updates `zbus` to v3 because
`DBusProxy::receive_name_owner_changed_with_args` was added in 3.6.
=> bluetooth: listen to NameOwnerChanged event

Cargo.lock, Cargo.toml, src/blocks/focused_window.rs, src/blocks/focused_window/sway_ipc.rs, src/blocks/focused_window/wlr_toplevel_management.rs, src/blocks/watson.rs, wl-protocol/wlr-foreign-toplevel-management-unstable-v1.xml
Closes #1683
I had to update dependencies because of a version conflict.
I tested this on `river`, but it should work on most (if not all) wlroots-based compositors.
=> POC: focused_window: add wlr_toplevel_management driver (and remove ristate)

Cargo.lock, Cargo.toml, src/blocks/apt.rs, src/blocks/custom.rs, src/blocks/custom_dbus.rs, src/blocks/dnf.rs, src/blocks/docker.rs, src/blocks/focused_window.rs, src/blocks/github.rs, src/blocks/load.rs, src/blocks/memory.rs, src/blocks/music.rs, src/blocks/net.rs, src/blocks/pacman.rs, src/blocks/rofication.rs, src/blocks/sound.rs, src/blocks/taskwarrior.rs, src/config.rs, src/escape.rs, src/formatting.rs, src/formatting/config.rs, src/formatting/formatter.rs, src/formatting/parse.rs, src/formatting/template.rs, src/main.rs
Closes #1605
Closes #1624
Closes #1655
```toml
format = " $speed_down.eng(3,_B,K) $frequency.eng(4) $ssid.rot-str(10,0.2) "
```
Becomes
```toml
format = " $speed_down.eng(w:3,p:K,hide_unit:true) $frequency.eng(w:4) $ssid.str(max_w:10, rot_interval:0.2) "
```
Also use `nom` for parsing. The downside of this is that error messages are even worse now. But this should be fixable.
=> formatting: implement named arguments instead of positional

README.md, src/config.rs, src/main.rs, src/protocol.rs, src/protocol/i3bar_block.rs, src/protocol/i3bar_event.rs, src/widget.rs
Fixes #1539
```toml
[[block]]
block = "sound"
driver = "pulseaudio"
format = " $icon {$volume |}"
device_kind = "sink"
merge_with_next = true # <===
[[block]]
block = "sound"
driver = "pulseaudio"
format = " $icon {$volume |}"
device_kind = "source"
[block.theme_overrides]
idle_fg = { link = "warning_fg" }
idle_bg = { link = "warning_bg" }
warning_fg = { link = "idle_fg" }
warning_bg = { link = "idle_bg" }
```
in `i3bar-river`:
=> implement merge_with_next option

src/blocks/music.rs, src/wrappers.rs
"Number of microseconds to seek..." doesn't seem very user-friendly. In addition, the default value was clearly wrong (0.001 second).
Renamed `seek_step` to `seek_step_secs` not to silently break configs.
=> music: remove seek_step, add seek_step_secs

src/blocks/time.rs, src/formatting.rs, src/formatting/config.rs, src/formatting/formatter.rs, src/formatting/parse.rs, src/formatting/value.rs
Resolves #1708 ~~(well will)~~
I added a new parsers for the current time.
~~Issues to resolve~~
~~* icon doesn't work~~
~~* Instead of parsing the format each iteration it seems that a `StrftimeItems` could be used, but the lifetimes eluded me so far.~~
=> Add datetime value parser

files/icons/awesome.toml, files/icons/awesome5.toml, files/icons/awesome6.toml, files/icons/material-nf.toml, files/icons/material.toml, src/blocks.rs, src/blocks/backlight.rs, src/blocks/battery.rs, src/blocks/cpu.rs, src/blocks/kdeconnect.rs, src/blocks/sound.rs, src/config.rs, src/formatting/template.rs, src/icons.rs, src/util.rs
This is a breaking change but it will make adding "animated" icons a non-breaking change in the future.
=> allow icon configs to contain lists instead of strings, remove icons such as bat_N

src/blocks/rofication.rs
The command "num" needs to be LF terminated or the server never responds.
```
#socat - UNIX-CONNECT:/tmp/rofi_notification_daemon
num  => No LF
```
Wait forever
```
#socat - UNIX-CONNECT:/tmp/rofi_notification_daemon
num:
0,0
```
This seems to have been broken during the initial transition to 0.30 ( https://github.com/greshake/i3status-rust/commit/2bd5df75f40eb3d64212c482cab359727a42a95d )
=> Rofication block: Add required LF to num

src/formatting.rs, src/formatting/formatter.rs
Instead of having to specify both min_width and max_width to the same value when we want a constant length for a string (so the bar doesn't change, for example because we're now playing a song with a much longer name) we should be able to just specify the width we want.
This diff just adds 'width' or 'w' which is course sets min_width and max_width to the same value.
=> Add width, w for constant width on formatter

src/blocks/cpu.rs
This avoids a panic on systems where cpu frequency is unavailable.
(Such as on this M1 mac running Asahi Linux)
=> cpu: make frequency optional

src/blocks/watson.rs
While reading state, neither we nor watson seem to perfom locking of the state file. Thus, parsing the state file can fail unexpectedly. This would lead to an error in the block, making it unusable until i3status-rust is restartet. This change introduces the empty state as a default to avoid this behavior.
fixes #1775
=> blocks/watson: Avoid error on race condition while reading state

doc/manual_install.md
=> Document install settings for non-glibc systems

Cargo.lock, Cargo.toml, src/netlink.rs
I don't know what `NL80211_BSS_INFORMATION_ELEMENTS` is, but on my machine the first two bytes don't make sense, then goes SSID up to byte 1.
Fixes #1607
=> net: try to fetch ssid from NL80211_BSS_INFORMATION_ELEMENTS

man/i3status-rs.1, src/blocks/backlight.rs
Fixes #1760
If you are on a system without `org.freedesktop.login1`, setting the brightness was failing. This change enables fallback to write to the brightness file.
=> backlight: dbus fallback to sysfs

src/util.rs
I have my config in `~/.config/i3/status` next to i3 config and the latest upgrade fails with `Configuration file '~/.config/i3/status' not found`, and it took a while to track down the cause. It looks like a recent change forces all files to have a `'.toml` extension even if they exist without it or have a different extension.
=> Stop find_files requiring a specific extension

src/blocks/battery.rs, src/blocks/battery/sysfs.rs, src/blocks/battery/upower.rs
Add the option to select batteries by model instead of path. Example:
```
[[block]]
block = "battery"
interval = 10
driver = "upower"
model = "MX Ergo Multi-Device Trackball"
format = "🖱 $icon $percentage"
[[block]]
block = "battery"
interval = 10
driver = "sysfs"
model = "Framewor"
format = "$icon $percentage"
```
Testing recovery:
With this block:
```
[[block]]
block = "battery"
interval = 10
driver = "upower"
model = "MX Ergo Multi-Device Trackball"
format = "🖱 $icon $percentage"
missing_format = "🖱Is gone!"
```
Disconnecting the mouse and reconnecting it works fine, with the missing_format being shown for the duration of the mouse disconnection.
```
[{"full_text":"","color":"#458588FF","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":"🖱  …
```
=> Filter battery selection by model

src/blocks/external_ip.rs, src/blocks/prelude.rs, src/main.rs
This is a first idea for how we could do IPv4 in `external_ip` to solve #1761.
In the first commit, i just added a `use_ipv4` option that makes the block use IPv4.
But here's where i need some advice: Thinking about it, it might be more useful to have an `$ipv4` placeholder, which would allow showing both at the same time (without requiring 2 blocks).
I implemented this in the second commit. It works, but has the disadvantage of all other info (country, city, ASN, etc.) still belonging to the original (potentially-non-v4) IP. The only alternative i see here would be doubling all format placeholders (`v4_country`, `v4_city`, `v4_asn`), which isn't very nice either. There's also the disadvantage of both requests being made even if only `$ipv4` is used.
Or is it just easier to go with commit …
=> Allow showing or forcing IPv4 in `external_ip`

src/blocks/hueshift.rs
`max` was returning the larger value between `config.step` and 500, basically defaulting step to 500 or higher. `min` will return the smaller of `config.step` and 500, meaning the value will never go above 500, but may be lower.
Fix for #1826
=> fix: hueshift block step now maxes at 500

src/blocks/bluetooth.rs, src/wrappers.rs
Closes #1830
Example:
```toml
[[block]]
block = "bluetooth"
[block.battery_state]
"0..20" = "critical"
"21..70" = "warning"
"71..100" = "good"
```
=> bluetooth: add battery_state config option

src/blocks/cpu.rs
`"failed to read /proc/sta"` -> `"failed to read /proc/stat"`
=> cpu: fix error message typo in read_proc_stat

src/blocks/apt.rs
If your system language is set to something else than English, then the upgradable package count failes.
E.g. in German the key word ist "aktualisierbar".
Fortunately this is easily fixable by setting the env variable LANG to C.
=> Force apt output to be in default language

doc/manual_install.md
Otherwise, compilation fails at link time with:
`ld: cannot find -lnotmuch: No such file or directory`
Steps to reproduce:
`cargo build --release --features notmuch`
=> manual_install.md: optional notmuch block depends upon libnotmuch.so

examples/README.md
Fix the Switch GTK Theme example in the examples/README.md to conform to the new syntax of i3status-rust 0.30.0
=> docs: fix Switch GTK Theme example

Cargo.lock, Cargo.toml, src/blocks/backlight.rs
Fixes #1771
There's still no device rescanning to detect if a device has been removed/added.
I left the default behavior when no device is specified to match only the first device, but would like others thoughts if we should make it match all devices by default (that's what I'd suggest). Most people who didn't specify a device already probably only have a single monitor so matching everything won't make an impact to them.
=> backlight: Add regex device name matching

src/formatting.rs
0.5 _was_ the default, before rotation was merged into `.str()`.
=> formatting.rs: fix `rot_interval` default in docs

Cargo.lock
Fixes https://github.com/greshake/i3status-rust/issues/1870
=> calibright config: do not look for files relative to the CWD.

files/icons/material-nf.toml, src/blocks.rs, src/blocks/temperature.rs
[**Update material-nf**](https://github.com/greshake/i3status-rust/commit/2225b77edcf240551105cf8a91c2fa5ea0534465) 
The `nf-mdi-*` icons have been deprecated. This commit exchanges them
for their `nf-md` counterparts.
[**Add thermometer progression for material-nf**](https://github.com/greshake/i3status-rust/commit/11778c6638c26f94113fd3b626098aff7f7fcab2)
=> Theme material-nf3

cspell.yaml, src/blocks/sound/pulseaudio.rs
Fixes #334
Ideally this should be reflected in the UI, but for now I suppose it is better than just stalling the block.
Also, apparently there is a bug in `libpulse_binding` as it is possible to segfault w/o `unsafe`.
=> sound: reconnect to pa

src/formatting.rs, src/formatting/formatter.rs
Tested using `format = " $icon {$signal_strength.bar(v:true) $ssid} "` on `net` block. Seems to work. Should work on anything else too.
Fix #1886
=> Add vertical option for bar formatting (▁ ▂ ▃ ▄ ▅ ▆ ▇)

src/blocks/keyboard_layout.rs
I've done my best to make an idiomatic addition to parse keyboard layout variants in the xkbmap driver for the keyboard_layout block. This means all 4 drivers have support for variants and layouts.
I've been testing with it myself between two "us" layouts with different variants.
=> keyboard_layout block: Add support for keyboard layout variant to xkbmap driver

src/blocks/memory.rs
Based on conversation in #1930
=> Update default memory format

src/blocks/amd_gpu.rs
=> amd_gpu: select device automatically

cspell.yaml, examples/README.md
Hi, these are examples to make package maintainer's job easier. Or more stressful.
=> Add maintainer helper block examples

Cargo.lock, Cargo.toml, src/blocks/sound/pulseaudio.rs
Since Rust 1.72, Sender<T> implements Sync if T: Send, which lets us use it instead of crossbeam-channel - one less dependency.
Bumps MSRV to 1.72.
=> switch to std::sync::mpsc from crossbeam-channel

Cargo.lock, Cargo.toml, src/blocks.rs, src/blocks/backlight.rs, src/blocks/weather.rs, src/click.rs, src/errors.rs, src/formatting.rs, src/formatting/formatter.rs, src/formatting/template.rs, src/lib.rs, src/main.rs
- Remove `kind` and `block` fields from `Error`.
- Removed `block` field is replaced by `BlockError` struct.
- Represent formatting errors (such as "placeholder not found") as an enum with thiserror macro.
- Merge `ResultExt` and `OptionExt` into `ErrorContext`.
=> Simplify some error handling and make it more structured

cspell.yaml, src/blocks/weather.rs, src/blocks/weather/met_no.rs, src/blocks/weather/open_weather_map.rs, src/util.rs
=> Add weather forecast

src/blocks/time.rs
https://github.com/chronotope/chrono/issues/272 has been resolved. `tzset()` is no longer needed.
=> time: remove tzset() call

src/blocks/apt.rs
blocks/apt: Added config option `ignore_updates_regex` to filter out undesired packages from the list of outdated packages.
See #1958
=> blocks/apt: Added config option `ignore_updates_regex` to filter the list of updates

src/blocks/focused_window.rs
This problem manifests in the man page when looking at the *next* block's documentation. Currently that is the `github` block, which is almost entirely subsumed into this `focus_window` Example toml.
=> blocks/focused_window: Close code block in markdown doc

README.md
It seems that the link in the `README.md` to the home-manager options is dead.
Looks like maybe [this commit](https://github.com/nix-community/home-manager/commit/6c82b1c9ce4dfb882cf53d1b9a09f01fbc9b0ba1) switched the pages to use `xhtml`.
=> docs(readme): update home-manager options link

src/blocks/kdeconnect.rs
=> rework kdeconnect

examples/config.toml, src/blocks/cpu.rs
Closes #1915 
```toml
[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90
```
=> blocks/cpu: Add critical/warning/info values in configuration

src/blocks/keyboard_layout.rs, src/blocks/keyboard_layout/xkb_switch.rs
Closes #1512 
Reimplemented XkbSwitch to show keyboard layout and variant
Example:
```toml
[[block]]
block = "keyboard_layout"
driver = "xkbswitch"
interval = 15
```
=> Add xkbswitch support for keyboard layout

src/config.rs, src/themes.rs
Also switch from container-level `serde(default)` to field-level `serde(default)` in some places to avoid unnecessary file reads and deserialization, because container-level attribute creates a default instance of the entire struct and thus calls `default()` even for specified fields. In particullar, this change avoids reading `plain.toml` if theme is set.
Fixes #1992
=> default theme to "plain" even if [theme] section is absent

src/blocks.rs, src/blocks/music.rs, src/click.rs, src/wrappers.rs
Before:
```toml
[[block.click]]
button = "middle"
action = "toggle_format"
[[block.click]]
button = "middle"
widget = "play_pause_btn"
action = "toggle_format"
```
After:
```toml
[[block.click]]
button = "middle"
widget = "*"
action = "toggle_format"
```
=> config: allow widget=<regex> in click handlers

Cargo.lock, Cargo.toml, src/blocks/sound.rs, src/wrappers.rs
As suggested in https://github.com/greshake/i3status-rust/pull/1961#issuecomment-1945072008.
`indexmap` was a transient dependency anyway.
=> drop serde_with dependency

src/blocks/time.rs
Closes #1991 
Instead of snapping to the start (`:00`) of the next minute, it snaps to the nearest multiple of the interval value. 
For example, if the interval value is `5` and the config is initialized at `:17`, the sequence shown will be `:17`, `:20`, `:25` and so on.
=> Adjust phase of time block

Cargo.lock, Cargo.toml, cspell.yaml, src/blocks/battery/upower.rs, src/blocks/bluetooth.rs, src/blocks/custom_dbus.rs, src/blocks/hueshift.rs, src/blocks/kdeconnect.rs, src/blocks/kdeconnect/battery.rs, src/blocks/kdeconnect/connectivity_report.rs, src/blocks/keyboard_layout/kbdd_bus.rs, src/blocks/keyboard_layout/locale_bus.rs, src/blocks/music.rs, src/blocks/music/zbus_mpris.rs, src/blocks/music/zbus_playerctld.rs, src/blocks/notify.rs, src/blocks/service_status.rs, src/blocks/tea_timer.rs
And temporarily use a fork of `calibright` because some combination of dependencies cause one of the dependencies not to compile.
~~Blocked by: https://github.com/bim9262/calibright/pull/15~~
=> update zbus to v4

src/blocks/bluetooth.rs, src/blocks/custom.rs, src/blocks/custom_dbus.rs, src/blocks/focused_window.rs, src/blocks/kdeconnect.rs, src/blocks/music.rs, src/blocks/pomodoro.rs, src/blocks/privacy.rs, src/blocks/sound.rs, src/blocks/tea_timer.rs, src/formatting.rs
Escaping the `"`s in `<code>` blocks prevents the `"` from being rendered as `“` or `”` (left and right double quotation marks).
Standardized using `\|` instead of `&vert`
=> Escape " in code blocks, replace &vert; with \|

cspell.yaml, src/blocks/memory.rs
To make zswap work, you need at least Linux kernel version 5.19 or higher.
=> blocks/memory: add zram, zswap support

src/blocks/kdeconnect.rs
With 2 devices connected to `kdeconnectd` and specifying `device_id` in i3rs config, it currently does the opposite of what is expected and ignores the `device_id` when looking for devices :laughing:
=> Fix device_id in kdeconnect block

src/blocks/amd_gpu.rs
Improve error message when supplied device is non existent.
Fix #2034
=> amd_gpu: better error message on device not found

src/blocks/privacy.rs, src/blocks/weather.rs, src/util.rs
This avoids creating a temporary hashmap.
=> map! macro: add @extend mode to extend an existing map

src/themes.rs
- Before: `data did not match any variant of untagged enum ColorOrLink`.
- After: `'not a color' is not a valid RGBA color. Cause: invalid digit found in string`.
=> manually impl Deserialize for ColorOrLink for better error messages

src/blocks/disk_space.rs, src/blocks/memory.rs, src/formatting.rs, src/formatting/formatter/eng.rs, src/formatting/template.rs
Closes #1957
Show the cpu block only if utilization is above 10%:
```toml
[[block]]
block = "cpu"
format = " $icon $utilization.eng(range:10..) |"
```
Support disjoint ranges? Would it be useful? How? Maybe by allowing multiple `range` arguments.
=> formatting(eng): add `range` parameter

Cargo.lock
Removes transient dependency `futures-executor`
=> Update calibright to 0.1.7

Cargo.lock, Cargo.toml, src/formatting/formatter/datetime.rs
Fixes #1965
What is the right behavior if the timezone abbreviation fails? Right now it will display an error, but a few other options would be to still display the old "`TimezoneName`" (ex -05:00)  or fall back to printing just the long name like America/Chicago
Perhaps something like:
```diff
diff --git a/src/formatting/formatter/datetime.rs b/src/formatting/formatter/datetime.rs
index 7b288b906..bf506a184 100644
--- a/src/formatting/formatter/datetime.rs
+++ b/src/formatting/formatter/datetime.rs
@@ -121,25 +121,19 @@ impl TimezoneName<Tz> for Tz {
impl TimezoneName<Local> for Local {
fn timezone_name(datetime: &DateTime<Local>) -> Result<Box<str>> {
-        match iana_time_zone::get_timezone()
-            .error("Could not get local timezone")?
-            .parse::<Tz>()
- …
```
=> formatter[datetime]: fix timezone abbreviation (%Z)

cspell.yaml, src/blocks/weather.rs, src/blocks/weather/nws.rs
I prefer using the US National Weather Service to get my forecast information in the US, especially as it means I don't need an API key like OpenWeatherMap requires. Thanks to the previous work that was done to support met.no, it was quite easy to add in support for NWS as an additional service option. Would it be alright to merge this support in?
=> block[weather]: Add support for the US National Weather Service

src/blocks/weather/nws.rs
australian_apparent_temp requires m/s not km/h.
convert temperature back to fahrenheit if original temperature is in fahrenheit
@Cognoscan does this capture the changes that you mentioned on your PR?
=> block[weather]: Fix nws apparent temperature

src/blocks/weather.rs, src/blocks/weather/met_no.rs, src/blocks/weather/nws.rs, src/blocks/weather/open_weather_map.rs
Moved `combine_forecasts` that @Cognoscan just added from nws to be used by all of the backends (now `Forecast::new`).
Added `ForecastAggregateSegment` which has the same members as `ForecastAggregate`, but makes all of the fields Optional since met.no does not promise that they're included in the response.
=> block[weather]: Remove redundant code

src/blocks/music.rs
If left unescaped, these quotes got rendered with some special characters which cause trouble when copy-pasting the command  into a terminal.
I did a quick check, looks like other single/double quots, vertical bars, and double dashes in `<code>` blocks are escaped properly.
| Before | After |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/545befe5-fa88-4757-998f-066a88fe7e55) | ![image](https://github.com/user-attachments/assets/a46d839c-5c3f-4236-8181-97bab3c58a00) |
=> Escape quotes and double dashes in <code> blocks

src/blocks/battery.rs, src/blocks/tea_timer.rs, src/blocks/uptime.rs, src/formatting.rs, src/formatting/formatter.rs, src/formatting/formatter/duration.rs, src/formatting/formatter/eng.rs, src/formatting/value.rs
TODO: document duration formatter.
Any thoughts on the names of the arguments, the format, or the defaults?
The formatted can be used by the battery, uptime, tea_timer and pomodoro blocks.
=> Add duration formatter

Cargo.lock, Cargo.toml, cspell.yaml, src/blocks.rs, src/blocks/calendar.rs, src/blocks/calendar/auth.rs, src/blocks/calendar/caldav.rs
This PR adds a Calendar block that displays upcoming events.
=> Add Calendar block

doc/themes.md, src/protocol.rs, src/themes.rs
=> Add start_separator

Cargo.lock, Cargo.toml, src/blocks/weather.rs, src/blocks/weather/met_no.rs, src/blocks/weather/nws.rs, src/blocks/weather/open_weather_map.rs
ref #715 
Opted to include into existing weather block instead of creating standalone block.
Implemented for both OpenWeatherMap and MetNo providers
=> extend weather block to show sunset and sunrise

src/blocks/notify.rs
If swaync is inhibited, treat notifications as paused.
Setting paused to false will clear dnd + inhibited.
The results of the futures for inhibited are ignored as this was not present before swaync v0.8.0.
=> block[notify]: swaync add support for inhibited status

Cargo.lock
Fix check to see if `amdgpu_bl` is used (https://github.com/bim9262/calibright/issues/18)
=> [deps]: Update calibright

src/blocks/battery/upower.rs, src/blocks/keyboard_layout/sway.rs, src/netlink.rs
Better readability, requires Rust 1.82
=> use is_none_or instread of map_or(true,...)

src/protocol.rs
This change preserves the end separator colors when separator_fg and separator_bg are set to "auto", and makes it use the configured colors when they are set.
resolves https://github.com/greshake/i3status-rust/issues/2110
before: 
after:
=> Make end_separator respect separator_fg and separator_bg

src/formatting.rs, src/formatting/formatter/eng.rs
Fixes #2113
Example usage (will show the icon but only if $status >= 1):
```toml
[[block]]
block = "maildir"
format = " $icon $status.eng(range:1..,show:false)|"
```
=> formatting(eng): add show parameter

cspell.yaml, doc/themes.md, src/themes.rs, src/themes/color.rs, src/themes/xresources.rs
Adds support to retrieve simple color definitions from `~/.Xresources` with a new prefix in the color definitions in theme overrides, e.g.,
```
[theme.overrides]
idle-bg = "x:background"
```
would look for a line like
```
*background: #feedda
```
in `~/.Xresources`.
=> Support x:<name> syntax to fetch color definition from .Xresources

src/blocks.rs, src/blocks/disk_iostats.rs
Reads disk stats from sysfs.
TODO:
See: https://docs.kernel.org/admin-guide/iostats.html
=> block[disk_iostats]: new block

Cargo.lock, Cargo.toml, src/blocks/pomodoro.rs
Changes:
* Set block state based on pomodoro state
* Set icon based on pomodoro state
* Allow pomodos to be counted with arabic numeral or tally marks #2003 
The previous config will still be valid with the current config since there are new formats for the various states.
Ideally this will be merged after the format duration is added so that we don't have an additional inflection point in the config.
=> pomodoro: Overhaul block

src/blocks.rs, src/blocks/calendar/auth.rs, src/blocks/calendar/caldav.rs, src/blocks/cpu.rs, src/blocks/custom.rs, src/blocks/memory.rs, src/blocks/net.rs, src/blocks/privacy/pipewire.rs, src/blocks/sound/pulseaudio.rs, src/blocks/time.rs, src/blocks/watson.rs, src/blocks/weather.rs, src/click.rs, src/escape.rs, src/formatting/formatter.rs, src/formatting/formatter/datetime.rs, src/formatting/formatter/str.rs, src/formatting/parse.rs, src/formatting/scheduling.rs, src/lib.rs, src/netlink.rs, src/protocol/i3bar_event.rs, src/signals.rs, src/subprocess.rs, src/util.rs
Checks for use Trait where the Trait is only used for its methods and not referenced by a path directly.
Traits imported that aren’t used directly can be imported anonymously with use Trait as _. It is more explicit, avoids polluting the current scope with unused names and can be useful to show which imports are required for traits.
=> warn clippy::unused_trait_names

README.md, src/blocks.rs, src/blocks/external_ip.rs, src/blocks/weather.rs, src/blocks/weather/met_no.rs, src/blocks/weather/nws.rs, src/blocks/weather/open_weather_map.rs, src/config.rs, src/geolocator.rs, src/geolocator/ip2location.rs, src/geolocator/ipapi.rs, src/lib.rs
=> Add global geolocator

Cargo.lock, Cargo.toml
This pins the swayipc-async dependency to the latest commit of the swayipc-rs repo.
Tracking: https://github.com/JayceFayne/swayipc-rs/issues/63
Resolves #2127
=> [deps]: Update swayipc-async

src/netlink.rs
This pr changes the way the default route and corresponding default interface are chosen
possible problem in [issue 2117](https://github.com/greshake/i3status-rust/issues/2117)
1. default route is set by looking for any attrtibure that indicates the route being default route(by looking for Rta::Gateway)
2. and simply took the first matching route’s interface index and the corresponding interface as default
What this fix does :
1. Now, every default route(routes where rtm_dst_len == 0) is looked at 
2. and its interface index and a “metric” value is looked at 
3. whichever default route has the smallest metric, the interfave at its interface index is taken  as the default interface
This should ensure that if multiple interfaces have “default routes,” the one with the lowest metric is …
=> [fix] Updated the way default interfaces are chosen in `netlink.rs`

src/blocks/calendar/caldav.rs
fixes calendar retrieval if caldav server replies with multiple `<comp ..>` entities eg.
```xml
<?xml version="1.0" encoding="utf-8"?>
<D:multistatus xmlns:D="DAV:" xmlns:a="urn:ietf:params:xml:ns:caldav">
<D:response>
<D:href>/SOGo/dav/___redacted___/Calendar/</D:href>
<D:propstat>
<D:status>HTTP/1.1 200 OK</D:status>
<D:prop>
<D:displayname>Calendar</D:displayname>
<D:resourcetype>
<D:collection/>
</D:resourcetype>
<n1:supported-calendar-component-set xmlns:n1="urn:ietf:params:xml:ns:caldav" xmlns:D="DAV:">
<n1:comp name="VEVENT"/>
<n1:comp name="VTODO"/>
</n1:supported-calendar-component-set>
</D:prop>
</D:propstat>
</D:response>
<D:response>
....
```
this is the case for sogo caldav service and apparently for nexcloud accoring to: #2175
=> blocks[calendar]: parse multiple comp within support-calendar-componet-set

src/blocks/service_status.rs
Oneshot systemd services transition directly from activating to dead/inactive and never show up as "active". This change treats these services as "active" when "activating" because that's likely what the user wants. Otherwise, backup tasks, etc. never show up as active services in i3status-rs.
=> Treat oneshot systemd services as "active" when "activating"
